//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DisputeEvent.
const (
	ACKNOWLEDGECHARGEBACK    DisputeEvent = "ACKNOWLEDGE_CHARGEBACK"
	APPEAL                   DisputeEvent = "APPEAL"
	CLOSE                    DisputeEvent = "CLOSE"
	FILECHARGEBACK           DisputeEvent = "FILE_CHARGEBACK"
	ISSUEFINALCREDIT         DisputeEvent = "ISSUE_FINAL_CREDIT"
	ISSUEREFUND              DisputeEvent = "ISSUE_REFUND"
	LOSECHARGEBACK           DisputeEvent = "LOSE_CHARGEBACK"
	OPENINVESTIGATION        DisputeEvent = "OPEN_INVESTIGATION"
	RECEIVEQUESTIONNAIRE     DisputeEvent = "RECEIVE_QUESTIONNAIRE"
	REVERSEPROVISIONALCREDIT DisputeEvent = "REVERSE_PROVISIONAL_CREDIT"
	SENDQUESTIONNAIRE        DisputeEvent = "SEND_QUESTIONNAIRE"
	SUBMITEVIDENCE           DisputeEvent = "SUBMIT_EVIDENCE"
	WINCHARGEBACK            DisputeEvent = "WIN_CHARGEBACK"
)

// Valid indicates whether the value is a known member of the DisputeEvent enum.
func (e DisputeEvent) Valid() bool {
	switch e {
	case ACKNOWLEDGECHARGEBACK:
		return true
	case APPEAL:
		return true
	case CLOSE:
		return true
	case FILECHARGEBACK:
		return true
	case ISSUEFINALCREDIT:
		return true
	case ISSUEREFUND:
		return true
	case LOSECHARGEBACK:
		return true
	case OPENINVESTIGATION:
		return true
	case RECEIVEQUESTIONNAIRE:
		return true
	case REVERSEPROVISIONALCREDIT:
		return true
	case SENDQUESTIONNAIRE:
		return true
	case SUBMITEVIDENCE:
		return true
	case WINCHARGEBACK:
		return true
	default:
		return false
	}
}

// Defines values for DisputeState.
const (
	CHARGEBACKACKNOWLEDGED    DisputeState = "CHARGEBACK_ACKNOWLEDGED"
	CHARGEBACKFILED           DisputeState = "CHARGEBACK_FILED"
	CHARGEBACKLOST            DisputeState = "CHARGEBACK_LOST"
	CHARGEBACKWON             DisputeState = "CHARGEBACK_WON"
	CLOSED                    DisputeState = "CLOSED"
	EVIDENCESUBMITTED         DisputeState = "EVIDENCE_SUBMITTED"
	FASTREFUNDISSUED          DisputeState = "FAST_REFUND_ISSUED"
	FINALCREDITISSUED         DisputeState = "FINAL_CREDIT_ISSUED"
	INITIATED                 DisputeState = "INITIATED"
	INVESTIGATING             DisputeState = "INVESTIGATING"
	PROVISIONALCREDITISSUED   DisputeState = "PROVISIONAL_CREDIT_ISSUED"
	PROVISIONALCREDITREVERSED DisputeState = "PROVISIONAL_CREDIT_REVERSED"
	QUESTIONNAIRERECEIVED     DisputeState = "QUESTIONNAIRE_RECEIVED"
	QUESTIONNAIRESENT         DisputeState = "QUESTIONNAIRE_SENT"
	SEPANQAREFUNDISSUED       DisputeState = "SEPA_NQA_REFUND_ISSUED"
)

// Valid indicates whether the value is a known member of the DisputeState enum.
func (e DisputeState) Valid() bool {
	switch e {
	case CHARGEBACKACKNOWLEDGED:
		return true
	case CHARGEBACKFILED:
		return true
	case CHARGEBACKLOST:
		return true
	case CHARGEBACKWON:
		return true
	case CLOSED:
		return true
	case EVIDENCESUBMITTED:
		return true
	case FASTREFUNDISSUED:
		return true
	case FINALCREDITISSUED:
		return true
	case INITIATED:
		return true
	case INVESTIGATING:
		return true
	case PROVISIONALCREDITISSUED:
		return true
	case PROVISIONALCREDITREVERSED:
		return true
	case QUESTIONNAIRERECEIVED:
		return true
	case QUESTIONNAIRESENT:
		return true
	case SEPANQAREFUNDISSUED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAppealsExhausted    ErrorCode = "appeals-exhausted"
	ErrorCodeConcurrentUpdate    ErrorCode = "concurrent-update"
	ErrorCodeContractViolation   ErrorCode = "contract-violation"
	ErrorCodeIdempotencyKeyReuse ErrorCode = "idempotency-key-reuse"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidTransition   ErrorCode = "invalid-transition"
	ErrorCodeMalformedRequest    ErrorCode = "malformed-request"
	ErrorCodeNoRegime            ErrorCode = "no-regime"
	ErrorCodeNotFound            ErrorCode = "not-found"
	ErrorCodeUnauthenticated     ErrorCode = "unauthenticated"
	ErrorCodeUnavailable         ErrorCode = "unavailable"
	ErrorCodeUnknownRegime       ErrorCode = "unknown-regime"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAppealsExhausted:
		return true
	case ErrorCodeConcurrentUpdate:
		return true
	case ErrorCodeContractViolation:
		return true
	case ErrorCodeIdempotencyKeyReuse:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidTransition:
		return true
	case ErrorCodeMalformedRequest:
		return true
	case ErrorCodeNoRegime:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeUnavailable:
		return true
	case ErrorCodeUnknownRegime:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk          HealthStatus = "ok"
	HealthStatusUnavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for Regime.
const (
	EUPSD2CARD        Regime = "EU_PSD2_CARD"
	EUSEPADIRECTDEBIT Regime = "EU_SEPA_DIRECT_DEBIT"
	USREGE            Regime = "US_REG_E"
	USREGZ            Regime = "US_REG_Z"
)

// Valid indicates whether the value is a known member of the Regime enum.
func (e Regime) Valid() bool {
	switch e {
	case EUPSD2CARD:
		return true
	case EUSEPADIRECTDEBIT:
		return true
	case USREGE:
		return true
	case USREGZ:
		return true
	default:
		return false
	}
}

// ApplyEventRequest defines model for ApplyEventRequest.
type ApplyEventRequest struct {
	Actor *string      `json:"actor,omitempty"`
	Event DisputeEvent `json:"event"`

	// Payload Event-specific facts, stored verbatim on the log entry.
	Payload *map[string]interface{} `json:"payload,omitempty"`
}

// CreateDisputeRequest defines model for CreateDisputeRequest.
type CreateDisputeRequest struct {
	// Actor Who opened it; defaults to customer.
	Actor         *string            `json:"actor,omitempty"`
	TransactionId openapi_types.UUID `json:"transactionId"`
}

// Dispute defines model for Dispute.
type Dispute struct {
	AccountId     openapi_types.UUID `json:"accountId"`
	AllowedEvents []DisputeEvent     `json:"allowedEvents"`
	Appeals       int                `json:"appeals"`
	Currency      string             `json:"currency"`

	// DisputedAmount Decimal as a string; never a float.
	//
	// Example: 125.4000
	DisputedAmount string             `json:"disputedAmount"`
	Events         []LoggedEvent      `json:"events"`
	Id             openapi_types.UUID `json:"id"`
	OpenedAt       time.Time          `json:"openedAt"`
	Regime         Regime             `json:"regime"`
	State          DisputeState       `json:"state"`
	TransactionId  openapi_types.UUID `json:"transactionId"`
	UpdatedAt      time.Time          `json:"updatedAt"`
	Version        int64              `json:"version"`
}

// DisputeEvent defines model for DisputeEvent.
type DisputeEvent string

// DisputeState defines model for DisputeState.
type DisputeState string

// ErrorCode Stable machine-readable failure identifier; branch on this, never on text.
type ErrorCode string

// FieldError defines model for FieldError.
type FieldError struct {
	// Field Example: /transactionId
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoggedEvent defines model for LoggedEvent.
type LoggedEvent struct {
	Actor string `json:"actor"`

	// Event A DisputeEvent, or OPENED for entry 1.
	Event      string                 `json:"event"`
	FromState  string                 `json:"fromState"`
	OccurredAt time.Time              `json:"occurredAt"`
	Payload    map[string]interface{} `json:"payload"`
	Seq        int                    `json:"seq"`
	ToState    DisputeState           `json:"toState"`
	TraceId    *string                `json:"traceId,omitempty"`
}

// Problem RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Problem struct {
	// AllowedEvents Present on invalid-transition; what the dispute accepts right now.
	AllowedEvents *[]DisputeEvent `json:"allowedEvents,omitempty"`

	// Code Stable machine-readable failure identifier; branch on this, never on text.
	Code   ErrorCode `json:"code"`
	Detail *string   `json:"detail,omitempty"`

	// Errors Field-level failures for contract-violation and business validation; field is a JSON pointer into the body, or query.x / header.x / path.x.
	Errors            *[]FieldError `json:"errors,omitempty"`
	Instance          *string       `json:"instance,omitempty"`
	RequestId         string        `json:"requestId"`
	RetryAfterSeconds *int          `json:"retryAfterSeconds,omitempty"`

	// Retryable true when the same request (unavailable) or a re-evaluated one (concurrent-update) can succeed later.
	Retryable bool   `json:"retryable"`
	Status    int    `json:"status"`
	Title     string `json:"title"`

	// Type urn:dispute-engine:error:<code>
	Type string `json:"type"`
}

// Regime defines model for Regime.
type Regime string

// DisputeId defines model for DisputeId.
type DisputeId = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type BadRequest = Problem

// NotFound RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type NotFound = Problem

// Unauthorized RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Unauthorized = Problem

// Unprocessable RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Unprocessable = Problem

// CreateDisputeParams defines parameters for CreateDispute.
type CreateDisputeParams struct {
	// IdempotencyKey Client-chosen key. Same key and body replays the original response; same key with a different body is 422.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ApplyDisputeEventParams defines parameters for ApplyDisputeEvent.
type ApplyDisputeEventParams struct {
	// IdempotencyKey Client-chosen key. Same key and body replays the original response; same key with a different body is 422.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateDisputeJSONRequestBody defines body for CreateDispute for application/json ContentType.
type CreateDisputeJSONRequestBody = CreateDisputeRequest

// ApplyDisputeEventJSONRequestBody defines body for ApplyDisputeEvent for application/json ContentType.
type ApplyDisputeEventJSONRequestBody = ApplyEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateDispute Open a dispute against a transaction
	// (POST /disputes)
	CreateDispute(w http.ResponseWriter, r *http.Request, params CreateDisputeParams)
	// GetDispute Current state and full event log
	// (GET /disputes/{disputeId})
	GetDispute(w http.ResponseWriter, r *http.Request, disputeId DisputeId)
	// ApplyDisputeEvent Apply a lifecycle event
	// (POST /disputes/{disputeId}/events)
	ApplyDisputeEvent(w http.ResponseWriter, r *http.Request, disputeId DisputeId, params ApplyDisputeEventParams)
	// GetHealthz Liveness
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness (database reachable)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateDispute operation middleware
func (siw *ServerInterfaceWrapper) CreateDispute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDisputeParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDispute(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDispute operation middleware
func (siw *ServerInterfaceWrapper) GetDispute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "disputeId" -------------
	var disputeId DisputeId

	err = runtime.BindStyledParameterWithOptions("simple", "disputeId", r.PathValue("disputeId"), &disputeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "disputeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDispute(w, r, disputeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyDisputeEvent operation middleware
func (siw *ServerInterfaceWrapper) ApplyDisputeEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "disputeId" -------------
	var disputeId DisputeId

	err = runtime.BindStyledParameterWithOptions("simple", "disputeId", r.PathValue("disputeId"), &disputeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "disputeId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyDisputeEventParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyDisputeEvent(w, r, disputeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/disputes", wrapper.CreateDispute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/disputes/{disputeId}", wrapper.GetDispute)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/disputes/{disputeId}/events", wrapper.ApplyDisputeEvent)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableApplicationProblemPlusJSONResponse Problem

type CreateDisputeRequestObject struct {
	Params CreateDisputeParams
	Body   *CreateDisputeJSONRequestBody
}

type CreateDisputeResponseObject interface {
	VisitCreateDisputeResponse(w http.ResponseWriter) error
}

type CreateDispute201JSONResponse Dispute

func (response CreateDispute201JSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateDispute400ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateDispute401ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateDispute404ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response CreateDispute422ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetDisputeRequestObject struct {
	DisputeId DisputeId `json:"disputeId"`
}

type GetDisputeResponseObject interface {
	VisitGetDisputeResponse(w http.ResponseWriter) error
}

type GetDispute200JSONResponse Dispute

func (response GetDispute200JSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDispute401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetDispute401ApplicationProblemPlusJSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDispute404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDispute404ApplicationProblemPlusJSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEventRequestObject struct {
	DisputeId DisputeId `json:"disputeId"`
	Params    ApplyDisputeEventParams
	Body      *ApplyDisputeEventJSONRequestBody
}

type ApplyDisputeEventResponseObject interface {
	VisitApplyDisputeEventResponse(w http.ResponseWriter) error
}

type ApplyDisputeEvent200JSONResponse Dispute

func (response ApplyDisputeEvent200JSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent400ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent401ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent404ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent409ApplicationProblemPlusJSONResponse Problem

func (response ApplyDisputeEvent409ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent422ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse Health

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse Health

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateDispute Open a dispute against a transaction
	// (POST /disputes)
	CreateDispute(ctx context.Context, request CreateDisputeRequestObject) (CreateDisputeResponseObject, error)
	// GetDispute Current state and full event log
	// (GET /disputes/{disputeId})
	GetDispute(ctx context.Context, request GetDisputeRequestObject) (GetDisputeResponseObject, error)
	// ApplyDisputeEvent Apply a lifecycle event
	// (POST /disputes/{disputeId}/events)
	ApplyDisputeEvent(ctx context.Context, request ApplyDisputeEventRequestObject) (ApplyDisputeEventResponseObject, error)
	// GetHealthz Liveness
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness (database reachable)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateDispute operation middleware
func (sh *strictHandler) CreateDispute(w http.ResponseWriter, r *http.Request, params CreateDisputeParams) {
	var request CreateDisputeRequestObject

	request.Params = params

	var body CreateDisputeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDispute(ctx, request.(CreateDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDisputeResponseObject); ok {
		if err := validResponse.VisitCreateDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDispute operation middleware
func (sh *strictHandler) GetDispute(w http.ResponseWriter, r *http.Request, disputeId DisputeId) {
	var request GetDisputeRequestObject

	request.DisputeId = disputeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDispute(ctx, request.(GetDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDisputeResponseObject); ok {
		if err := validResponse.VisitGetDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyDisputeEvent operation middleware
func (sh *strictHandler) ApplyDisputeEvent(w http.ResponseWriter, r *http.Request, disputeId DisputeId, params ApplyDisputeEventParams) {
	var request ApplyDisputeEventRequestObject

	request.DisputeId = disputeId
	request.Params = params

	var body ApplyDisputeEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyDisputeEvent(ctx, request.(ApplyDisputeEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyDisputeEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyDisputeEventResponseObject); ok {
		if err := validResponse.VisitApplyDisputeEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFltc9u4Ef4rGLQzzU2pF7+kvcifFIl22DiyT5KTmaYeDQyuRJxJgAFA2bqM/nsHACmSIv2Wu7r3SSKB",
	"BXaf3X2wWH7HVCSp4MC1woPvOCWSJKBB2qcxU2mmIQjNA+N4gFOiI+xhThLAAxzuxj0s4VvGJIR4oGUG",
	"HlY0goQYwaWQCdF4gLOMmZl6kxphpSXjK7zdejgIIUmFBk43H2FjZEJQVLJUM2F2HcUMuO7QSCjg6BY2",
	"XTQjCZh/iPAQ3YhwgySkMdkopCNAQrIV4yRGElQquIITpAqBO6YjRFDIlkuQwLWTZgodHx52sefsjICE",
	"IEtLKxp2jIpV+xJyfw58pSM8ODj82cMJ47vnprVbDxdKWYzfk3AK3zJQ2jxRwTVw+5ekacwoMRD0Uilu",
	"Ykj+/qsyeHyvbP5XCUs8wH/plX7suVHVu3RSbtM6op9IbNwCIZJu8y7eengi9KnIePiamkwEUhmNjKdE",
	"JilYRa44yXQkJPsNXlWZT0wpxlceyvgtF3ccCYkkrMUthEgDJ1zb6HMqplJQUIrcxPCaOn6BOO7kzrvJ",
	"NOJCI0IppNpogt6wMlRtvEvIFITtYe8ZA7lAElYsAbQU0qaPloQrQs2GP3VthuZ6GbWHaRpv/DVwXYnb",
	"VIoUpGYupgnVQro0XpIs1niA1UZpSJrZ72FY56g9hkfORHZbI5SSTSyIjQ0ShsxoSuLLihKOhOrIWemO",
	"SoGyJaNoSahWHlJaSAjRGuQN0SxBglsMYrFCwLXcdEulxc2vQDXebqt09zW34LoxzcMjCURDrvxL4KKZ",
	"0iKxDLTn/UggkQKHEDF9gnIJhbRAhUy3DeWKSx2dP83KVRPr4m2m5ka2WUdFxvWzdvUwiWNxB6F1lRVn",
	"GhL10vDIlyVSko1dNU2BxHaZfIhxDSuQZpBmUpps2ePyoxqTH7Xomh9/4TAxBjaPrTFQlpAYEYUIcmIn",
	"iMMaJCJoGQuijavgniSpoRB8cPi2e9zv9x/MkucDci5WqxzFNjzY85zhAm2oa5NDoqGjWQJtEo5IntJu",
	"6mYZXtFEwzO9O7NzfyCWPZylRusXWbIGqZjgNQHG9T+OsdeIob1kYa4eWrmVnYllDJZL71viVXKlEV2V",
	"OK04pmrafvLsguaRdPUL8gWeJUb3i0t/sggmn/3ZPDgbzoOLCfbwzJ+MF79cmXcXk8kwmPrYw1N/5Aef",
	"/cb7YDa78hdT//RqMsYePg3O/cXow3B65r8fjj5iDw9HHycXX8798dnewOzq/adgvvA/B2N/MjJrfQkm",
	"9SnnF7M9IbfdaTAZni9GU38czK1un/3pzF9cTi8+B7PgojY4MosYPS4v/eE5vm5xfi3iKugEk2AeDOe+",
	"MawC0uQMe7iGw2LmT+aNlzlkRrqp2cJaYiEbzuY5gOXLmX85XEx+GTYGSjQWBuu9VxWwzUiB7cJhPd+f",
	"/uViUn9xfjGbWy+2KdpiRI78uMB53IqvL6WQIxFCkzRnroxJCI0Yh44EEtoXS8LiTAJiIXDNlgzkCbqR",
	"hNPIndhMeTm3mke4d9ya+y2z9aQRpCZZsIeTogDu5AWwSTDBtSRUd9ZMxLZ6wx7mQneWtij2MONrErOw",
	"Y9OW5RPyvO7AfUQy5Vangrts1R2Xn0a4coW4hU3H1mV2g86OK/Kys/qCrAmLDQJ2fw2Sk7gV01MGcWiB",
	"bZ7BSzNm/pSHTW+fexoLJqAUWUHl0HygOHCrlwJtfPMBSKyjpmY0AnqrHq7jvjf1aqxtGDZT1TwVt3vY",
	"XT9V4ORrtKlePUsfrt0ermvr8T1EVeq1BbjhXH9sq29bcaKD1hJuKUWyY6TGqKA24l50xj2zim4CDt/a",
	"SyktZj94oNO8y/CEl+BbcazhKiDlzl7ukdK4GjRt/i3uWg1XTU9H6N3x23+i/A6HQtCExaqL/DXIDbJx",
	"bzoHiizBVOAqEnfml6BMGX4KGVlxoTSjCilNNohxpEAakorFSqGMhyCLG3gQGq/vRdd+NVxX8FKCAq4N",
	"4zWp6QTdRUTbu0xeSuTXRIUkW0Xm4nhndvxDCmyac/lja5Skb++0Bsr2xDHzWqy1BNeJYQ1xcRoomzRN",
	"3nZdoUwxDkohiwxxmOx8RtC/ZhcTlApLqohxLSxWu2vxtwzkpnuPesg1g+xf0//q3j8btgont1XhXGnC",
	"aXs+76LigVEtN8OlBjkDKnj4wNXGTisaFHU0TWqjuwjcbdd2x/It0ZsKc/5koCBIQgfWJM7M6YkEB/Sm",
	"ccT9hCjhppdDAUIUE127id4IEQPhdbpuKqyZjuER1t+3IpN8kEd3B/iKcRjY8Bn8J+v3j6gJS/sPnr7h",
	"mtFCgZ2SeWRXkay6po1OprsrUHEa+VcLW72Ng6k/mi/G/ntbh/pXi8vZ+HAxGk5NuXQ1W0z9s4Vf/v13",
	"+7GlgGaS6c3MBJnjiRsgEuQw01ETovmub+UhplQGIUpBFu0skyiGtjgSnMKJCwZHUbYxopDg8QYxrVBE",
	"VNQtOp/Wp3bXEtlI69R1rBhfiqYmgdlddhQLS0qK2RLohsZQkGqS6TyF0xR4aDsbFQ77m0KW/g2Bdnf+",
	"GhQVO/JtEKDhZVC5aA1wv3vQ7RdXWpIyPMBH3X73yJ4TOrIg9vIt7EMqXKfGsDEpbpr1fg72au3yr+1U",
	"UE7p7bW5t9e7UHovws0jPcSX9Q5bm07beryb7N/vRB/2D/4wHQqIWvqXhafcHbaLpnnfXixLJtprtyMJ",
	"OpOuyncTDEvbNuxxv/+QLjvjepUeuxU5eFqk1oG2QsdPC+3650bg8PA5u1SbyDa5syQhcoMH+CIFbhu2",
	"+dm9Iua8QKTancUe1mRlgg/vgvfaLLOL5d733UeardFnBS1hfQb6R2O6/ETkwrkWT/3XiKd5SQ7d13Jv",
	"zVEjdwwi2+ixhLrM4rikqZc5qVd2+to5yPbfa/XY7/CZ92chreZXhWcx1qtEmFUL2aUhPKlX1KYEK7+Z",
	"2ML7T85L/Xev+bXKZKfLBKbcpyp3pUHm8maBo9X08Vy5WRaXyBWX6K7A9ffSqg00RMrCAxXXyQeSNLKd",
	"i98eI88P+ZT/YXi6LdoQvnSmGnyztFurEPHg63XV9nO2Bg5KVYzNv8s5U02zbfOopVM34/9iqN3bBsHb",
	"/tEr7DdEIZgS1H5JNeiWt6LHYTaKupvnm5BockMUIAmERvZC1Qp+fbV6Qf/12pCuK8odv2cyzsvtQa8X",
	"C0riSCg9+Ln/ro+319v/DgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
