//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DisputeEvent.
const (
	ACKNOWLEDGECHARGEBACK    DisputeEvent = "ACKNOWLEDGE_CHARGEBACK"
	APPEAL                   DisputeEvent = "APPEAL"
	CLOSE                    DisputeEvent = "CLOSE"
	FILECHARGEBACK           DisputeEvent = "FILE_CHARGEBACK"
	ISSUEFINALCREDIT         DisputeEvent = "ISSUE_FINAL_CREDIT"
	ISSUEREFUND              DisputeEvent = "ISSUE_REFUND"
	LOSECHARGEBACK           DisputeEvent = "LOSE_CHARGEBACK"
	OPENINVESTIGATION        DisputeEvent = "OPEN_INVESTIGATION"
	RECEIVEQUESTIONNAIRE     DisputeEvent = "RECEIVE_QUESTIONNAIRE"
	REVERSEPROVISIONALCREDIT DisputeEvent = "REVERSE_PROVISIONAL_CREDIT"
	SENDQUESTIONNAIRE        DisputeEvent = "SEND_QUESTIONNAIRE"
	SUBMITEVIDENCE           DisputeEvent = "SUBMIT_EVIDENCE"
	WINCHARGEBACK            DisputeEvent = "WIN_CHARGEBACK"
)

// Valid indicates whether the value is a known member of the DisputeEvent enum.
func (e DisputeEvent) Valid() bool {
	switch e {
	case ACKNOWLEDGECHARGEBACK:
		return true
	case APPEAL:
		return true
	case CLOSE:
		return true
	case FILECHARGEBACK:
		return true
	case ISSUEFINALCREDIT:
		return true
	case ISSUEREFUND:
		return true
	case LOSECHARGEBACK:
		return true
	case OPENINVESTIGATION:
		return true
	case RECEIVEQUESTIONNAIRE:
		return true
	case REVERSEPROVISIONALCREDIT:
		return true
	case SENDQUESTIONNAIRE:
		return true
	case SUBMITEVIDENCE:
		return true
	case WINCHARGEBACK:
		return true
	default:
		return false
	}
}

// Defines values for DisputeState.
const (
	CHARGEBACKACKNOWLEDGED    DisputeState = "CHARGEBACK_ACKNOWLEDGED"
	CHARGEBACKFILED           DisputeState = "CHARGEBACK_FILED"
	CHARGEBACKLOST            DisputeState = "CHARGEBACK_LOST"
	CHARGEBACKWON             DisputeState = "CHARGEBACK_WON"
	CLOSED                    DisputeState = "CLOSED"
	EVIDENCESUBMITTED         DisputeState = "EVIDENCE_SUBMITTED"
	FASTREFUNDISSUED          DisputeState = "FAST_REFUND_ISSUED"
	FINALCREDITISSUED         DisputeState = "FINAL_CREDIT_ISSUED"
	INITIATED                 DisputeState = "INITIATED"
	INVESTIGATING             DisputeState = "INVESTIGATING"
	PROVISIONALCREDITISSUED   DisputeState = "PROVISIONAL_CREDIT_ISSUED"
	PROVISIONALCREDITREVERSED DisputeState = "PROVISIONAL_CREDIT_REVERSED"
	QUESTIONNAIRERECEIVED     DisputeState = "QUESTIONNAIRE_RECEIVED"
	QUESTIONNAIRESENT         DisputeState = "QUESTIONNAIRE_SENT"
	SEPANQAREFUNDISSUED       DisputeState = "SEPA_NQA_REFUND_ISSUED"
)

// Valid indicates whether the value is a known member of the DisputeState enum.
func (e DisputeState) Valid() bool {
	switch e {
	case CHARGEBACKACKNOWLEDGED:
		return true
	case CHARGEBACKFILED:
		return true
	case CHARGEBACKLOST:
		return true
	case CHARGEBACKWON:
		return true
	case CLOSED:
		return true
	case EVIDENCESUBMITTED:
		return true
	case FASTREFUNDISSUED:
		return true
	case FINALCREDITISSUED:
		return true
	case INITIATED:
		return true
	case INVESTIGATING:
		return true
	case PROVISIONALCREDITISSUED:
		return true
	case PROVISIONALCREDITREVERSED:
		return true
	case QUESTIONNAIRERECEIVED:
		return true
	case QUESTIONNAIRESENT:
		return true
	case SEPANQAREFUNDISSUED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeAppealsExhausted    ErrorCode = "appeals-exhausted"
	ErrorCodeConcurrentUpdate    ErrorCode = "concurrent-update"
	ErrorCodeContractViolation   ErrorCode = "contract-violation"
	ErrorCodeIdempotencyKeyReuse ErrorCode = "idempotency-key-reuse"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidTransition   ErrorCode = "invalid-transition"
	ErrorCodeMalformedRequest    ErrorCode = "malformed-request"
	ErrorCodeNoRegime            ErrorCode = "no-regime"
	ErrorCodeNotFound            ErrorCode = "not-found"
	ErrorCodeRateLimited         ErrorCode = "rate-limited"
	ErrorCodeUnauthenticated     ErrorCode = "unauthenticated"
	ErrorCodeUnavailable         ErrorCode = "unavailable"
	ErrorCodeUnknownRegime       ErrorCode = "unknown-regime"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeAppealsExhausted:
		return true
	case ErrorCodeConcurrentUpdate:
		return true
	case ErrorCodeContractViolation:
		return true
	case ErrorCodeIdempotencyKeyReuse:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidTransition:
		return true
	case ErrorCodeMalformedRequest:
		return true
	case ErrorCodeNoRegime:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeUnavailable:
		return true
	case ErrorCodeUnknownRegime:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk          HealthStatus = "ok"
	HealthStatusUnavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for Regime.
const (
	EUPSD2CARD        Regime = "EU_PSD2_CARD"
	EUSEPADIRECTDEBIT Regime = "EU_SEPA_DIRECT_DEBIT"
	USREGE            Regime = "US_REG_E"
	USREGZ            Regime = "US_REG_Z"
)

// Valid indicates whether the value is a known member of the Regime enum.
func (e Regime) Valid() bool {
	switch e {
	case EUPSD2CARD:
		return true
	case EUSEPADIRECTDEBIT:
		return true
	case USREGE:
		return true
	case USREGZ:
		return true
	default:
		return false
	}
}

// ApplyEventRequest defines model for ApplyEventRequest.
type ApplyEventRequest struct {
	Actor *string      `json:"actor,omitempty"`
	Event DisputeEvent `json:"event"`

	// Payload Event-specific facts, stored verbatim on the log entry.
	Payload *map[string]interface{} `json:"payload,omitempty"`
}

// CreateDisputeRequest defines model for CreateDisputeRequest.
type CreateDisputeRequest struct {
	// Actor Who opened it; defaults to customer.
	Actor         *string            `json:"actor,omitempty"`
	TransactionId openapi_types.UUID `json:"transactionId"`
}

// Dispute defines model for Dispute.
type Dispute struct {
	AccountId     openapi_types.UUID `json:"accountId"`
	AllowedEvents []DisputeEvent     `json:"allowedEvents"`
	Appeals       int                `json:"appeals"`
	Currency      string             `json:"currency"`

	// DisputedAmount Decimal as a string; never a float.
	//
	// Example: 125.4000
	DisputedAmount string             `json:"disputedAmount"`
	Events         []LoggedEvent      `json:"events"`
	Id             openapi_types.UUID `json:"id"`
	OpenedAt       time.Time          `json:"openedAt"`
	Regime         Regime             `json:"regime"`
	State          DisputeState       `json:"state"`
	TransactionId  openapi_types.UUID `json:"transactionId"`
	UpdatedAt      time.Time          `json:"updatedAt"`
	Version        int64              `json:"version"`
}

// DisputeEvent defines model for DisputeEvent.
type DisputeEvent string

// DisputeState defines model for DisputeState.
type DisputeState string

// ErrorCode Stable machine-readable failure identifier; branch on this, never on text.
type ErrorCode string

// FieldError defines model for FieldError.
type FieldError struct {
	// Field Example: /transactionId
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoggedEvent defines model for LoggedEvent.
type LoggedEvent struct {
	Actor string `json:"actor"`

	// Event A DisputeEvent, or OPENED for entry 1.
	Event      string                 `json:"event"`
	FromState  string                 `json:"fromState"`
	OccurredAt time.Time              `json:"occurredAt"`
	Payload    map[string]interface{} `json:"payload"`
	Seq        int                    `json:"seq"`
	ToState    DisputeState           `json:"toState"`
	TraceId    *string                `json:"traceId,omitempty"`
}

// Problem RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Problem struct {
	// AllowedEvents Present on invalid-transition; what the dispute accepts right now.
	AllowedEvents *[]DisputeEvent `json:"allowedEvents,omitempty"`

	// Code Stable machine-readable failure identifier; branch on this, never on text.
	Code   ErrorCode `json:"code"`
	Detail *string   `json:"detail,omitempty"`

	// Errors Field-level failures for contract-violation and business validation; field is a JSON pointer into the body, or query.x / header.x / path.x.
	Errors            *[]FieldError `json:"errors,omitempty"`
	Instance          *string       `json:"instance,omitempty"`
	RequestId         string        `json:"requestId"`
	RetryAfterSeconds *int          `json:"retryAfterSeconds,omitempty"`

	// Retryable true when the same request (unavailable) or a re-evaluated one (concurrent-update) can succeed later.
	Retryable bool   `json:"retryable"`
	Status    int    `json:"status"`
	Title     string `json:"title"`

	// Type urn:dispute-engine:error:<code>
	Type string `json:"type"`
}

// Regime defines model for Regime.
type Regime string

// SessionBlob Ciphertext the frontend server produced; the API stores it without being able to read it.
type SessionBlob struct {
	Ciphertext []byte    `json:"ciphertext"`
	ExpiresAt  time.Time `json:"expiresAt"`

	// Sid The realm's session id from the ID token
	Sid *string `json:"sid,omitempty"`

	// Subject The analyst's subject at the realm
	Subject *string `json:"subject,omitempty"`

	// TenantId Set once the session belongs to a signed-in analyst; informational.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`
}

// TenantSummary defines model for TenantSummary.
type TenantSummary struct {
	// EmailDomains Work-email domains that map to this tenant at sign-in.
	EmailDomains []string           `json:"emailDomains"`
	Id           openapi_types.UUID `json:"id"`

	// Issuer OIDC issuer of the tenant's realm.
	Issuer *string `json:"issuer,omitempty"`
	Name   string  `json:"name"`
	Slug   string  `json:"slug"`
}

// DisputeId defines model for DisputeId.
type DisputeId = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type BadRequest = Problem

// NotFound RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type NotFound = Problem

// TooManyRequests RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Unauthorized = Problem

// Unprocessable RFC 9457 problem details. Every field is safe to show to a user; diagnostics stay in server logs under requestId.
type Unprocessable = Problem

// CreateDisputeParams defines parameters for CreateDispute.
type CreateDisputeParams struct {
	// IdempotencyKey Client-chosen key. Same key and body replays the original response; same key with a different body is 422.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ApplyDisputeEventParams defines parameters for ApplyDisputeEvent.
type ApplyDisputeEventParams struct {
	// IdempotencyKey Client-chosen key. Same key and body replays the original response; same key with a different body is 422.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// DeleteSessionsParams defines parameters for DeleteSessions.
type DeleteSessionsParams struct {
	Sid      *string             `form:"sid,omitempty" json:"sid,omitempty"`
	TenantId *openapi_types.UUID `form:"tenantId,omitempty" json:"tenantId,omitempty"`
	Subject  *string             `form:"subject,omitempty" json:"subject,omitempty"`
}

// CreateDisputeJSONRequestBody defines body for CreateDispute for application/json ContentType.
type CreateDisputeJSONRequestBody = CreateDisputeRequest

// ApplyDisputeEventJSONRequestBody defines body for ApplyDisputeEvent for application/json ContentType.
type ApplyDisputeEventJSONRequestBody = ApplyEventRequest

// PutSessionJSONRequestBody defines body for PutSession for application/json ContentType.
type PutSessionJSONRequestBody = SessionBlob

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateDispute Open a dispute against a transaction
	// (POST /disputes)
	CreateDispute(w http.ResponseWriter, r *http.Request, params CreateDisputeParams)
	// GetDispute Current state and full event log
	// (GET /disputes/{disputeId})
	GetDispute(w http.ResponseWriter, r *http.Request, disputeId DisputeId)
	// ApplyDisputeEvent Apply a lifecycle event
	// (POST /disputes/{disputeId}/events)
	ApplyDisputeEvent(w http.ResponseWriter, r *http.Request, disputeId DisputeId, params ApplyDisputeEventParams)
	// GetHealthz Liveness
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// DeleteSessions End every session matching a realm session id or a tenant's subject
	// (DELETE /internal/sessions)
	DeleteSessions(w http.ResponseWriter, r *http.Request, params DeleteSessionsParams)
	// DeleteSession Remove a session
	// (DELETE /internal/sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID)
	// GetSession Fetch a session blob that has not expired
	// (GET /internal/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID)
	// PutSession Store or replace an opaque session blob
	// (PUT /internal/sessions/{sessionId})
	PutSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID)
	// ListTenants Active tenants with what the sign-in page needs to find their realm
	// (GET /internal/tenants)
	ListTenants(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness (database reachable)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateDispute operation middleware
func (siw *ServerInterfaceWrapper) CreateDispute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDisputeParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDispute(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDispute operation middleware
func (siw *ServerInterfaceWrapper) GetDispute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "disputeId" -------------
	var disputeId DisputeId

	err = runtime.BindStyledParameterWithOptions("simple", "disputeId", r.PathValue("disputeId"), &disputeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "disputeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDispute(w, r, disputeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyDisputeEvent operation middleware
func (siw *ServerInterfaceWrapper) ApplyDisputeEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "disputeId" -------------
	var disputeId DisputeId

	err = runtime.BindStyledParameterWithOptions("simple", "disputeId", r.PathValue("disputeId"), &disputeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "disputeId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyDisputeEventParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyDisputeEvent(w, r, disputeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSessions operation middleware
func (siw *ServerInterfaceWrapper) DeleteSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSessionsParams

	// ------------- Optional query parameter "sid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sid", r.URL.Query(), &params.Sid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tenantId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenantId", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenantId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject", r.URL.Query(), &params.Subject, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSession operation middleware
func (siw *ServerInterfaceWrapper) PutSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/disputes", wrapper.CreateDispute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/disputes/{disputeId}", wrapper.GetDispute)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/disputes/{disputeId}/events", wrapper.ApplyDisputeEvent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/internal/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/internal/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/internal/sessions/{sessionId}", wrapper.PutSession)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/internal/sessions", wrapper.DeleteSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/internal/tenants", wrapper.ListTenants)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableApplicationProblemPlusJSONResponse Problem

type CreateDisputeRequestObject struct {
	Params CreateDisputeParams
	Body   *CreateDisputeJSONRequestBody
}

type CreateDisputeResponseObject interface {
	VisitCreateDisputeResponse(w http.ResponseWriter) error
}

type CreateDispute201JSONResponse Dispute

func (response CreateDispute201JSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateDispute400ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateDispute401ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateDispute404ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response CreateDispute422ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDispute429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response CreateDispute429ApplicationProblemPlusJSONResponse) VisitCreateDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetDisputeRequestObject struct {
	DisputeId DisputeId `json:"disputeId"`
}

type GetDisputeResponseObject interface {
	VisitGetDisputeResponse(w http.ResponseWriter) error
}

type GetDispute200JSONResponse Dispute

func (response GetDispute200JSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDispute401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetDispute401ApplicationProblemPlusJSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDispute404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDispute404ApplicationProblemPlusJSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDispute429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetDispute429ApplicationProblemPlusJSONResponse) VisitGetDisputeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEventRequestObject struct {
	DisputeId DisputeId `json:"disputeId"`
	Params    ApplyDisputeEventParams
	Body      *ApplyDisputeEventJSONRequestBody
}

type ApplyDisputeEventResponseObject interface {
	VisitApplyDisputeEventResponse(w http.ResponseWriter) error
}

type ApplyDisputeEvent200JSONResponse Dispute

func (response ApplyDisputeEvent200JSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent400ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent401ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent404ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent409ApplicationProblemPlusJSONResponse Problem

func (response ApplyDisputeEvent409ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent422ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ApplyDisputeEvent429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ApplyDisputeEvent429ApplicationProblemPlusJSONResponse) VisitApplyDisputeEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionsRequestObject struct {
	Params DeleteSessionsParams
}

type DeleteSessionsResponseObject interface {
	VisitDeleteSessionsResponse(w http.ResponseWriter) error
}

type DeleteSessions200JSONResponse struct {
	Deleted int `json:"deleted"`
}

func (response DeleteSessions200JSONResponse) VisitDeleteSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessions400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteSessions400ApplicationProblemPlusJSONResponse) VisitDeleteSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteSessions401ApplicationProblemPlusJSONResponse) VisitDeleteSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
	SessionId openapi_types.UUID `json:"sessionId"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteSession401ApplicationProblemPlusJSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSessionRequestObject struct {
	SessionId openapi_types.UUID `json:"sessionId"`
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse SessionBlob

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSession401ApplicationProblemPlusJSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetSession404ApplicationProblemPlusJSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutSessionRequestObject struct {
	SessionId openapi_types.UUID `json:"sessionId"`
	Body      *PutSessionJSONRequestBody
}

type PutSessionResponseObject interface {
	VisitPutSessionResponse(w http.ResponseWriter) error
}

type PutSession204Response struct {
}

func (response PutSession204Response) VisitPutSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutSession400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutSession400ApplicationProblemPlusJSONResponse) VisitPutSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PutSession401ApplicationProblemPlusJSONResponse) VisitPutSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenantsRequestObject struct {
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse []TenantSummary

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListTenants401ApplicationProblemPlusJSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse Health

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse Health

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateDispute Open a dispute against a transaction
	// (POST /disputes)
	CreateDispute(ctx context.Context, request CreateDisputeRequestObject) (CreateDisputeResponseObject, error)
	// GetDispute Current state and full event log
	// (GET /disputes/{disputeId})
	GetDispute(ctx context.Context, request GetDisputeRequestObject) (GetDisputeResponseObject, error)
	// ApplyDisputeEvent Apply a lifecycle event
	// (POST /disputes/{disputeId}/events)
	ApplyDisputeEvent(ctx context.Context, request ApplyDisputeEventRequestObject) (ApplyDisputeEventResponseObject, error)
	// GetHealthz Liveness
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// DeleteSessions End every session matching a realm session id or a tenant's subject
	// (DELETE /internal/sessions)
	DeleteSessions(ctx context.Context, request DeleteSessionsRequestObject) (DeleteSessionsResponseObject, error)
	// DeleteSession Remove a session
	// (DELETE /internal/sessions/{sessionId})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// GetSession Fetch a session blob that has not expired
	// (GET /internal/sessions/{sessionId})
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// PutSession Store or replace an opaque session blob
	// (PUT /internal/sessions/{sessionId})
	PutSession(ctx context.Context, request PutSessionRequestObject) (PutSessionResponseObject, error)
	// ListTenants Active tenants with what the sign-in page needs to find their realm
	// (GET /internal/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// GetReadyz Readiness (database reachable)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateDispute operation middleware
func (sh *strictHandler) CreateDispute(w http.ResponseWriter, r *http.Request, params CreateDisputeParams) {
	var request CreateDisputeRequestObject

	request.Params = params

	var body CreateDisputeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDispute(ctx, request.(CreateDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDisputeResponseObject); ok {
		if err := validResponse.VisitCreateDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDispute operation middleware
func (sh *strictHandler) GetDispute(w http.ResponseWriter, r *http.Request, disputeId DisputeId) {
	var request GetDisputeRequestObject

	request.DisputeId = disputeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDispute(ctx, request.(GetDisputeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDispute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDisputeResponseObject); ok {
		if err := validResponse.VisitGetDisputeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyDisputeEvent operation middleware
func (sh *strictHandler) ApplyDisputeEvent(w http.ResponseWriter, r *http.Request, disputeId DisputeId, params ApplyDisputeEventParams) {
	var request ApplyDisputeEventRequestObject

	request.DisputeId = disputeId
	request.Params = params

	var body ApplyDisputeEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyDisputeEvent(ctx, request.(ApplyDisputeEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyDisputeEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyDisputeEventResponseObject); ok {
		if err := validResponse.VisitApplyDisputeEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSessions operation middleware
func (sh *strictHandler) DeleteSessions(w http.ResponseWriter, r *http.Request, params DeleteSessionsParams) {
	var request DeleteSessionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSessions(ctx, request.(DeleteSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionsResponseObject); ok {
		if err := validResponse.VisitDeleteSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID) {
	var request DeleteSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID) {
	var request GetSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutSession operation middleware
func (sh *strictHandler) PutSession(w http.ResponseWriter, r *http.Request, sessionId openapi_types.UUID) {
	var request PutSessionRequestObject

	request.SessionId = sessionId

	var body PutSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutSession(ctx, request.(PutSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutSessionResponseObject); ok {
		if err := validResponse.VisitPutSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(w http.ResponseWriter, r *http.Request) {
	var request ListTenantsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx, request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		if err := validResponse.VisitListTenantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFppc9s2+v8qGPz/M0lnqSOO223kV4rEJNo6sivJyc5mPRqIfCSiJgEGAGWrHn/3HRy8RMpHk7p9JZEE",
	"iOf8PRdvccCTlDNgSuLBLU6JIAkoEOZqTGWaKZiE+oIyPMApURH2MCMJ4AEOi+ceFvA1owJCPFAiAw/L",
	"IIKE6I1rLhKi8ABnGdUr1S7Vm6USlG3w3Z2HJyEkKVfAgt0vsNN7QpCBoKmiXJ86iikw1QkiLoGhK9h1",
	"0ZwkoP8hwkK04uEOCUhjspNIRYC4oBvKSIwEyJQzCSdI5huuqYoQQSFdr0EAU3Y3lej46KiLPctnBCQE",
	"UXJaobCjSazyl5CbU2AbFeHBq6OfPZxQVlw3ub3zcE6UkfFbEs7gawZS6auAMwXM/CVpGtOAaBH0UsFX",
	"MST/+E1qedxWDv9/AWs8wP/XK/XYs09l79zusofWJfqRxFotECJhD+/iOw9PuXrHMxY+JyVTjmQWRFpT",
	"PBMBGEIWnH8kbOcEI5+TnkUESAEjTL2QuXDQKgs3oNCaC2NeQSaM5SSUZQq07cgUmDpBApTYDdcKxBwC",
	"zkKJpDbJ6wgYUhwpsUNkQyjTdmZNzPA209s6Zl+dB2c8lCnYgNDk3nn4gpFMRVzQ3+FZNfWRSknZxkMZ",
	"u2L8miEukIAtv4LQScy4JjYkpoIHICVZxfCcNH6GOO44y15lCjGuEAkCSJWmBL2kpR8bMBCQSQjbMcHT",
	"DDKOBGxoAoXylSBMkkAf+EPXwJejS5M9TNN452+BqYpTp4KnIBS1Dk8CxYXFuDXJYoUHWO6kgqQJjR6G",
	"rZPaffJwMG2O1ZtSsos5MbZBwpBqSkl8XiHCInRdcmZ3R6YQ0DUN0JoESnpIKi4gRFsQK6JogjgzMoj5",
	"BgFTYtctiear3yBQ+O6uGgu+OA4uG8s8PBJAFDjinyKuIJOKJwae97QfccRTYBAiqk6Q2yG16+V7um1S",
	"rqjUxrqHQ1aVxfr2NlYdk23cBTxj6lGnepjEMb+G0KjKbKcKEvlU83CvJUKQnXlrmgKJZRveeNhCXbDb",
	"C3Sva2HudQutLjcIh4lmsBnTxxDQhMSISESQ3XaCGGxBIILWMSdKqwpuSJJqCMGvjn7sHvf7/YNe8niB",
	"nPLNxkmxTR70ccqwhjZUtcUhUdBRNIG2HRZIHqJuZldpXFFEwSO1Ozdr/4AtezhLNdVP4mQLQlLOahso",
	"Uz8dY69hQ3vOQm2yuLFvtiyWNli+ep8Tr+IrDeuq2GlFMVXW9p2nMJp73NXPwRdYlmjaz8796XIy/eTP",
	"F5P3w8XkbIo9PPen4+WvF/re2XQ6nMx87OGZP/Inn/zG/cl8fuEvZ/67i+kYe/jd5NRfjj4MZ+/9t8PR",
	"L9jDw9Ev07PPp/74/d6D+cXbj5PF0v80GfvTkX7X58m0vuT0bL63yR73bjIdni5HM388WRjaPvmzub88",
	"n519mswnZ7WHI/0STcf5uT88xZctyq9ZXEU6k+lkMRkufM1YRUjT99jDNTks5/500bjpRKZ3NylbGk6M",
	"yIbzhRNgeXPunw+X01+HjQelNJZa1nu3KsLWT3LZLq2sF/vLP59N6zdOz+YLo8U2QluYcJIf53Iet8rX",
	"F4KLEQ+hCZpzm8YkJIgog44AEpoba0LjTACiITBF1xTECVoJwoLIRmwqPYet+hJuLLY6vWUmn9QbA+0s",
	"2j2178c0ofYyyYuFjsuHtb9xpgQJVGdLeWySOexhxlVnbQoID1O2JTENO8aLqVvg3LwDNxHJpH17wJnL",
	"pzvWXfXmSrl1BbuOSdPMAZ0COlwWWr1BtoTGWiDmfAWCkbhVxO8oxKGRczMkr/Uz/aeMPb19KGq8MAEp",
	"yQYqMfRArmDfXm5og58PQGIVNSkLIgiu5OG07rZJV+PdGnAzWXVbfrUnu8uH8h33jjbSq6H1cCp3OM2t",
	"m/sQVZHY5OMagv2xScZNAopetWZ0a8GTAqAaT3lgLO5JIe+RSXVT4PC1PbNSfP4H43vgOjIPaAm+5lEO",
	"VwVSnuw5jZTM1UTTpt+89GqoavZuhN4c//hP5Eo6FIIiNJZd5G9B7JCxe1MpkzXohFxG/Fr/EpRJDVch",
	"JRvGpaKBRFKRHaIMSRAas2K+kShjIYi8IJ+EWut71rWfHNcJPBcggSkNgE1oOkHXEVGmtHGZhasaJRJ0",
	"E+k68lqf+F3y7cBB+33vKGOAKXG1KNsdR69r4dYAXCeGLcR5cJDGaZq4bTtomaQMpERGMsTKpNAZQf+a",
	"n01Ryg2oIsoUN7IqquSvGYhd9wb1kO1qmL+6V9i9ebTYKpjclpQzqQgL2v25sIoDT/eaMu3+aJbl/Yq6",
	"NLVruyZOBLaT6I5ELyvI+YMWBUECOrAlcaaDKeIM0MtGiPsBBYTpvlcAEKKYqFphuuI8BsLqcN0kWFEV",
	"wz2ov89FJtjAWXcH2IYyGBjzGfw36/dfB9oszT94uODVT3MCCiKdZVclWVVNG5zMioooj0b+xdIkc+PJ",
	"zB8tlmP/rUlL/Yvl+Xx8tBwNZzp7upgvZ/77pV/+/U9rnJ+D1MXE25ivWrrKNI1A6GzIqHUtTI8qzFEn",
	"FTzMAghPzNPh+cQ2QySiyvSLeKbQCijbIJOCKY50OoaoakJTUJxUizernQHhav/4p9c/H7fwATcpFSCf",
	"Eq8kDZss6+amABInLySSVjaIhpr1xHA5GSPFr4DpgMEFWpHgqhNEhDGINQrzTHXxgGVx3HZgZtXaeihh",
	"JN5J3VJ1y5CDW0MN9rDkiMQx4msXEEoCpfGVFSBgIYSHz7ctyEkL13PQsB+A9V7H9gpizjbShiBJNwzC",
	"DmU5oSeIMitnE+e72CvF/qieUEXlVfW1OcHCED7PkoSIXTNrgoTQeMwTQlkL0H/m4qpjlqDQrkFKh7KE",
	"pMigNJV5c5Yow2eHshomH8oZn9oPoVJmIJoUnk3GI2QfavWqen+dxElrAmfnLi3UyTjbPJz8GBLNUvcq",
	"ry7Hy7a2pYQgE1Tt5joiWeGvgAgQw0xFTcaGla43emk4DFEKwt32TIrDjOUVjdSIyAhCGygKYzO5hpTW",
	"9UpnbErJhEoTIQxZpdwipVIjHBBbGkDrEG0eEU2BhEBURhl7qPdCorxw0v5mIr7M+3KORcUdaVKzsRL8",
	"WoKQB0dn/+7MLVVucJabV0r1tenha19rEjwxNtORNCyzspiuIdgFMeR5ZZIpl8WkKeiBi0tN3IYXEpkM",
	"WKNXtwhZg7yHgXwTBzW6V1pPA9zvvur28yYfSSke4Nfdfve1SZVVZEyj544wFym3vWvtuCTvvdU73Nir",
	"TVe/tGdD5ZLe3lT07rKIpm95uLtnqvK0aUprG/6u7lA6AdofXB71X303GnIRtUx0ck3Zrl4XzdyYl6/L",
	"ZGxvOosEqEzYvoddoBNVM5g67vcP0VIw16uMZM2WVw9vqc3kzKbjhzcV41a94ejoMadUx2pm15uHd+0P",
	"Uw3U5dEGn6XAzOjLlT16PKkhqTrnwh5WZKONFhdGf6lfU/hA77b4FuBOU7SBFnd4D+qP+kL5JYJ1g5od",
	"9p/DDhclqHSf0yy+WcEjN6w2rXZT7K2zOC5h8WnK7ZWzlnbMMxPQWgn8Dbr2/i4g2ZzrPgohn8UyDVnI",
	"vDqvVgpv1lVvObU2vY6/OQ723zz31x7WE6i0HwvYLlKZhQVV9/FshV/W88jW8+g6l+tfBePGQBEpEySU",
	"d/4OOHdkmsy/3wfWH9ySP9Gs7RFtmjm3ItJ6ydJuLT/Hgy+XVd5P6RYYSFlh1n1RYVnNM9peXlHaXDMG",
	"BU2+x+b+PF/ZAC+T45p+V5niSltu7H+2U9Ym7duKivVJX8sdIMFV3/eR8a2Rs16XWgGGrZ8p1YuxfGVL",
	"0dVQ+wd+jRLCdmX1fw2iqP2fDbnq1nZbK6y+XN7VzM9noXY2UdCMEqL0gG5jmoEkTqq9FgMgRWlXqi23",
	"3HJu1W67vVv3z2Vaj7Ljpgsft7TwIeFbM5LjwlV8cEOlKpouf74oLQm6IVPQ3SIX7yBiHWT3+yFWtaV4",
	"IKCsYr56thzxKeJ9ByqISukaQm27KCI2/NlOVXhI7m1YWP8kuDDOb/ok+NLDadai4vOspuLvn+c1tPtQ",
	"hnfcNqTXrZ6/KVgZ4uyXm2lMAtBtKJ6SrxnUrOIRgOR6QAcTiFMq1cKt+UZ/fNT8qN5GbfQxm646DBTd",
	"5m022X0G4ddPtF+dFoNH15tFKdkAYgC2l7WmLNSPqSha5QcUo6cPu3vzuZld8Zekc+ZsI+Mf+6+f4bwh",
	"CiEFFpovfXUOWY7p7k8mNaF2FPoyJIqsiDRDiiAyE77WFHPfBKpNY2cCprlqQTMTsevYDnq9mAckjrhU",
	"g5/7b/r47vLufwMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
