// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPolicyVersion = `-- name: GetPolicyVersion :one
SELECT COALESCE((SELECT version FROM policy_versions), 0)::bigint AS version
`

func (q *Queries) GetPolicyVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getPolicyVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT team, role FROM team_members WHERE subject = $1 ORDER BY team
`

type ListMembershipsRow struct {
	Team string
	Role string
}

func (q *Queries) ListMemberships(ctx context.Context, subject string) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(&i.Team, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleGrants = `-- name: ListRoleGrants :many
SELECT team, role, action, amount_limit FROM role_grants ORDER BY team, role, action
`

type ListRoleGrantsRow struct {
	Team        string
	Role        string
	Action      string
	AmountLimit pgtype.Numeric
}

func (q *Queries) ListRoleGrants(ctx context.Context) ([]ListRoleGrantsRow, error) {
	rows, err := q.db.Query(ctx, listRoleGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleGrantsRow{}
	for rows.Next() {
		var i ListRoleGrantsRow
		if err := rows.Scan(
			&i.Team,
			&i.Role,
			&i.Action,
			&i.AmountLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingRules = `-- name: ListRoutingRules :many
SELECT position, rail, reason, risk_tier, min_amount, team FROM routing_rules ORDER BY position
`

type ListRoutingRulesRow struct {
	Position  int32
	Rail      *string
	Reason    *string
	RiskTier  *string
	MinAmount pgtype.Numeric
	Team      string
}

func (q *Queries) ListRoutingRules(ctx context.Context) ([]ListRoutingRulesRow, error) {
	rows, err := q.db.Query(ctx, listRoutingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutingRulesRow{}
	for rows.Next() {
		var i ListRoutingRulesRow
		if err := rows.Scan(
			&i.Position,
			&i.Rail,
			&i.Reason,
			&i.RiskTier,
			&i.MinAmount,
			&i.Team,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT slug, is_default FROM teams ORDER BY slug
`

type ListTeamsRow struct {
	Slug      string
	IsDefault bool
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(&i.Slug, &i.IsDefault); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
