// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlcgen

import (
	"context"
)

const getAccess = `-- name: GetAccess :one
SELECT
    COALESCE((SELECT version FROM policy_versions), 0)::bigint AS version,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('slug', slug, 'default', is_default) ORDER BY slug) FROM teams), '[]')::jsonb AS teams,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('team', team, 'role', role, 'action', action, 'limit', amount_limit::text)
        ORDER BY team, role, action) FROM role_grants), '[]')::jsonb AS grants,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('rail', rail, 'reason', reason, 'tier', risk_tier, 'min', min_amount::text, 'team', team)
        ORDER BY position) FROM routing_rules), '[]')::jsonb AS routing,
    COALESCE((SELECT jsonb_agg(jsonb_build_object('team', team, 'role', role) ORDER BY team)
        FROM team_members WHERE subject = $1::text), '[]')::jsonb AS members
`

type GetAccessRow struct {
	Version int64
	Teams   []byte
	Grants  []byte
	Routing []byte
	Members []byte
}

// One round trip for everything a decision needs; RLS limits every table to the tenant.
func (q *Queries) GetAccess(ctx context.Context, subject string) (GetAccessRow, error) {
	row := q.db.QueryRow(ctx, getAccess, subject)
	var i GetAccessRow
	err := row.Scan(
		&i.Version,
		&i.Teams,
		&i.Grants,
		&i.Routing,
		&i.Members,
	)
	return i, err
}
