// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countDisputesByState = `-- name: CountDisputesByState :many
SELECT tenant_id, regime, state, n FROM disputes_by_state
`

func (q *Queries) CountDisputesByState(ctx context.Context) ([]DisputesByState, error) {
	rows, err := q.db.Query(ctx, countDisputesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisputesByState{}
	for rows.Next() {
		var i DisputesByState
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.State,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTenantKeyByHash = `-- name: FindTenantKeyByHash :one
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE key_hash = $1
`

type FindTenantKeyByHashRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeyByHash(ctx context.Context, keyHash []byte) (FindTenantKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, findTenantKeyByHash, keyHash)
	var i FindTenantKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.RevokedAt,
	)
	return i, err
}

const findTenantKeysByPrefix = `-- name: FindTenantKeysByPrefix :many
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE prefix = $1
`

type FindTenantKeysByPrefixRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeysByPrefix(ctx context.Context, prefix string) ([]FindTenantKeysByPrefixRow, error) {
	rows, err := q.db.Query(ctx, findTenantKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTenantKeysByPrefixRow{}
	for rows.Next() {
		var i FindTenantKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispute = `-- name: GetDispute :one
SELECT id, tenant_id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at
FROM disputes
WHERE id = $1
`

type GetDisputeRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetDispute(ctx context.Context, id uuid.UUID) (GetDisputeRow, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i GetDisputeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Regime,
		&i.State,
		&i.Appeals,
		&i.Version,
		&i.TransactionID,
		&i.AccountID,
		&i.DisputedAmount,
		&i.Currency,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT scope, key, request_hash, status_code, response, created_at
FROM idempotency_keys
WHERE scope = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	Scope string
	Key   string
}

type GetIdempotencyKeyRow struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
	CreatedAt   time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByIssuer = `-- name: GetTenantByIssuer :one
SELECT id, slug FROM tenants WHERE oidc_issuer = $1
`

type GetTenantByIssuerRow struct {
	ID   uuid.UUID
	Slug string
}

func (q *Queries) GetTenantByIssuer(ctx context.Context, oidcIssuer *string) (GetTenantByIssuerRow, error) {
	row := q.db.QueryRow(ctx, getTenantByIssuer, oidcIssuer)
	var i GetTenantByIssuerRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getTenantByTenantKeyHash = `-- name: GetTenantByTenantKeyHash :one
SELECT id, tenant_id FROM tenant_keys
WHERE key_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

type GetTenantByTenantKeyHashRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetTenantByTenantKeyHash(ctx context.Context, keyHash []byte) (GetTenantByTenantKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getTenantByTenantKeyHash, keyHash)
	var i GetTenantByTenantKeyHashRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.account_id, t.rail, t.amount, t.currency, t.merchant, t.occurred_at, a.currency AS account_currency
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.id = $1
`

type GetTransactionRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Rail            string
	Amount          decimal.Decimal
	Currency        string
	Merchant        string
	OccurredAt      time.Time
	AccountCurrency string
}

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Rail,
		&i.Amount,
		&i.Currency,
		&i.Merchant,
		&i.OccurredAt,
		&i.AccountCurrency,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, tenant_id, holder_name, currency) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type InsertAccountParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	HolderName string
	Currency   string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.TenantID,
		arg.HolderName,
		arg.Currency,
	)
	return err
}

const insertDispute = `-- name: InsertDispute :exec
INSERT INTO disputes (id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
`

type InsertDisputeParams struct {
	ID             uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) error {
	_, err := q.db.Exec(ctx, insertDispute,
		arg.ID,
		arg.Regime,
		arg.State,
		arg.Appeals,
		arg.Version,
		arg.TransactionID,
		arg.AccountID,
		arg.DisputedAmount,
		arg.Currency,
		arg.OpenedAt,
	)
	return err
}

const insertDisputeEvent = `-- name: InsertDisputeEvent :one
INSERT INTO dispute_events (dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertDisputeEventParams struct {
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) InsertDisputeEvent(ctx context.Context, arg InsertDisputeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDisputeEvent,
		arg.DisputeID,
		arg.Seq,
		arg.Event,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.Payload,
		arg.IdempotencyKey,
		arg.TraceID,
		arg.OccurredAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (scope, key, request_hash, status_code, response)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyKeyParams struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.Response,
	)
	return err
}

const insertTenantKey = `-- name: InsertTenantKey :exec
INSERT INTO tenant_keys (id, tenant_id, key_hash, prefix, label, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTenantKeyParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	KeyHash   []byte
	Prefix    string
	Label     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertTenantKey(ctx context.Context, arg InsertTenantKeyParams) error {
	_, err := q.db.Exec(ctx, insertTenantKey,
		arg.ID,
		arg.TenantID,
		arg.KeyHash,
		arg.Prefix,
		arg.Label,
		arg.ExpiresAt,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (id, tenant_id, account_id, rail, amount, currency, merchant, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertTransactionParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	AccountID  uuid.UUID
	Rail       string
	Amount     decimal.Decimal
	Currency   string
	Merchant   string
	OccurredAt time.Time
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Rail,
		arg.Amount,
		arg.Currency,
		arg.Merchant,
		arg.OccurredAt,
	)
	return err
}

const listDisputeEvents = `-- name: ListDisputeEvents :many
SELECT id, dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at
FROM dispute_events
WHERE dispute_id = $1
ORDER BY seq
`

type ListDisputeEventsRow struct {
	ID             int64
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) ListDisputeEvents(ctx context.Context, disputeID uuid.UUID) ([]ListDisputeEventsRow, error) {
	rows, err := q.db.Query(ctx, listDisputeEvents, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputeEventsRow{}
	for rows.Next() {
		var i ListDisputeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Event,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Payload,
			&i.IdempotencyKey,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantKeys = `-- name: ListTenantKeys :many
SELECT id, tenant_id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys ORDER BY created_at
`

type ListTenantKeysRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListTenantKeys(ctx context.Context) ([]ListTenantKeysRow, error) {
	rows, err := q.db.Query(ctx, listTenantKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantKeysRow{}
	for rows.Next() {
		var i ListTenantKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, oidc_issuer FROM tenants ORDER BY name
`

type ListTenantsRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
}

func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OidcIssuer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :one
SELECT purge_idempotency_keys($1)::bigint AS n
`

func (q *Queries) PurgeIdempotencyKeys(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, purgeIdempotencyKeys, before)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const revokeTenantKey = `-- name: RevokeTenantKey :execrows
UPDATE tenant_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeTenantKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTenantKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchTenantKey = `-- name: TouchTenantKey :exec
UPDATE tenant_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchTenantKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTenantKey, id)
	return err
}

const updateDisputeState = `-- name: UpdateDisputeState :execrows
UPDATE disputes
SET state = $2, appeals = $3, version = version + 1, updated_at = $4
WHERE id = $1 AND version = $5
`

type UpdateDisputeStateParams struct {
	ID        uuid.UUID
	State     string
	Appeals   int32
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) UpdateDisputeState(ctx context.Context, arg UpdateDisputeStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDisputeState,
		arg.ID,
		arg.State,
		arg.Appeals,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name, slug, oidc_issuer) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, oidc_issuer = EXCLUDED.oidc_issuer
`

type UpsertTenantParams struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.Exec(ctx, upsertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OidcIssuer,
	)
	return err
}
