// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const bumpTenantRateWindow = `-- name: BumpTenantRateWindow :one
INSERT INTO tenant_rate_windows (tenant_id, window_start, count) VALUES ($1, $2, 1)
ON CONFLICT (tenant_id, window_start) DO UPDATE SET count = tenant_rate_windows.count + 1
RETURNING count
`

type BumpTenantRateWindowParams struct {
	TenantID    uuid.UUID
	WindowStart time.Time
}

func (q *Queries) BumpTenantRateWindow(ctx context.Context, arg BumpTenantRateWindowParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpTenantRateWindow, arg.TenantID, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDeadlinesOverdue = `-- name: CountDeadlinesOverdue :many
SELECT tenant_id, regime, kind, n FROM deadlines_overdue
`

func (q *Queries) CountDeadlinesOverdue(ctx context.Context) ([]DeadlinesOverdue, error) {
	rows, err := q.db.Query(ctx, countDeadlinesOverdue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadlinesOverdue{}
	for rows.Next() {
		var i DeadlinesOverdue
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.Kind,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDisputesByState = `-- name: CountDisputesByState :many
SELECT tenant_id, regime, state, n FROM disputes_by_state
`

func (q *Queries) CountDisputesByState(ctx context.Context) ([]DisputesByState, error) {
	rows, err := q.db.Query(ctx, countDisputesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisputesByState{}
	for rows.Next() {
		var i DisputesByState
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.State,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWebSession = `-- name: DeleteWebSession :execrows
DELETE FROM web_sessions WHERE id = $1
`

func (q *Queries) DeleteWebSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsBySid = `-- name: DeleteWebSessionsBySid :execrows
DELETE FROM web_sessions WHERE sid = $1
`

func (q *Queries) DeleteWebSessionsBySid(ctx context.Context, sid *string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsBySid, sid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsBySubject = `-- name: DeleteWebSessionsBySubject :execrows
DELETE FROM web_sessions WHERE tenant_id = $1 AND subject = $2
`

type DeleteWebSessionsBySubjectParams struct {
	TenantID pgtype.UUID
	Subject  *string
}

func (q *Queries) DeleteWebSessionsBySubject(ctx context.Context, arg DeleteWebSessionsBySubjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsBySubject, arg.TenantID, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsByTenant = `-- name: DeleteWebSessionsByTenant :execrows
DELETE FROM web_sessions WHERE tenant_id = $1
`

func (q *Queries) DeleteWebSessionsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsByTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTenantKeyByHash = `-- name: FindTenantKeyByHash :one
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE key_hash = $1
`

type FindTenantKeyByHashRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeyByHash(ctx context.Context, keyHash []byte) (FindTenantKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, findTenantKeyByHash, keyHash)
	var i FindTenantKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.RevokedAt,
	)
	return i, err
}

const findTenantKeysByPrefix = `-- name: FindTenantKeysByPrefix :many
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE prefix = $1
`

type FindTenantKeysByPrefixRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeysByPrefix(ctx context.Context, prefix string) ([]FindTenantKeysByPrefixRow, error) {
	rows, err := q.db.Query(ctx, findTenantKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTenantKeysByPrefixRow{}
	for rows.Next() {
		var i FindTenantKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispute = `-- name: GetDispute :one
SELECT id, tenant_id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at
FROM disputes
WHERE id = $1
`

type GetDisputeRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetDispute(ctx context.Context, id uuid.UUID) (GetDisputeRow, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i GetDisputeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Regime,
		&i.State,
		&i.Appeals,
		&i.Version,
		&i.TransactionID,
		&i.AccountID,
		&i.DisputedAmount,
		&i.Currency,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT scope, key, request_hash, status_code, response, created_at
FROM idempotency_keys
WHERE scope = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	Scope string
	Key   string
}

type GetIdempotencyKeyRow struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
	CreatedAt   time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByIssuer = `-- name: GetTenantByIssuer :one
SELECT id, slug FROM tenants WHERE oidc_issuer = $1 AND disabled_at IS NULL
`

type GetTenantByIssuerRow struct {
	ID   uuid.UUID
	Slug string
}

func (q *Queries) GetTenantByIssuer(ctx context.Context, oidcIssuer *string) (GetTenantByIssuerRow, error) {
	row := q.db.QueryRow(ctx, getTenantByIssuer, oidcIssuer)
	var i GetTenantByIssuerRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getTenantByTenantKeyHash = `-- name: GetTenantByTenantKeyHash :one
SELECT k.id, k.tenant_id FROM tenant_keys k
JOIN tenants t ON t.id = k.tenant_id AND t.disabled_at IS NULL
WHERE k.key_hash = $1 AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetTenantByTenantKeyHashRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetTenantByTenantKeyHash(ctx context.Context, keyHash []byte) (GetTenantByTenantKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getTenantByTenantKeyHash, keyHash)
	var i GetTenantByTenantKeyHashRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const getTenantCalendar = `-- name: GetTenantCalendar :one
SELECT COALESCE(settings->>'timezone', '')::text AS timezone,
       COALESCE(ARRAY(SELECT jsonb_array_elements_text(settings->'holidays')), '{}')::text[] AS holidays
FROM tenants WHERE id = current_tenant_id()
`

type GetTenantCalendarRow struct {
	Timezone string
	Holidays []string
}

func (q *Queries) GetTenantCalendar(ctx context.Context) (GetTenantCalendarRow, error) {
	row := q.db.QueryRow(ctx, getTenantCalendar)
	var i GetTenantCalendarRow
	err := row.Scan(&i.Timezone, &i.Holidays)
	return i, err
}

const getTenantCore = `-- name: GetTenantCore :one
SELECT COALESCE(settings->'core'->>'kind', '')::text AS kind, COALESCE(settings->'core', '{}'::jsonb)::jsonb AS settings
FROM tenants WHERE id = current_tenant_id()
`

type GetTenantCoreRow struct {
	Kind     string
	Settings []byte
}

func (q *Queries) GetTenantCore(ctx context.Context) (GetTenantCoreRow, error) {
	row := q.db.QueryRow(ctx, getTenantCore)
	var i GetTenantCoreRow
	err := row.Scan(&i.Kind, &i.Settings)
	return i, err
}

const getTenantKeyForTenant = `-- name: GetTenantKeyForTenant :one
SELECT id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys WHERE id = $1 AND tenant_id = $2
`

type GetTenantKeyForTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetTenantKeyForTenantRow struct {
	ID         uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) GetTenantKeyForTenant(ctx context.Context, arg GetTenantKeyForTenantParams) (GetTenantKeyForTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenantKeyForTenant, arg.ID, arg.TenantID)
	var i GetTenantKeyForTenantRow
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.account_id, t.rail, t.amount, t.currency, t.merchant, t.occurred_at, a.currency AS account_currency
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.id = $1
`

type GetTransactionRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Rail            string
	Amount          decimal.Decimal
	Currency        string
	Merchant        string
	OccurredAt      time.Time
	AccountCurrency string
}

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Rail,
		&i.Amount,
		&i.Currency,
		&i.Merchant,
		&i.OccurredAt,
		&i.AccountCurrency,
	)
	return i, err
}

const getWebSession = `-- name: GetWebSession :one
SELECT id, tenant_id, ciphertext, expires_at FROM web_sessions WHERE id = $1 AND expires_at > now()
`

type GetWebSessionRow struct {
	ID         uuid.UUID
	TenantID   pgtype.UUID
	Ciphertext []byte
	ExpiresAt  time.Time
}

func (q *Queries) GetWebSession(ctx context.Context, id uuid.UUID) (GetWebSessionRow, error) {
	row := q.db.QueryRow(ctx, getWebSession, id)
	var i GetWebSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Ciphertext,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, tenant_id, holder_name, currency) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type InsertAccountParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	HolderName string
	Currency   string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.TenantID,
		arg.HolderName,
		arg.Currency,
	)
	return err
}

const insertDeadline = `-- name: InsertDeadline :exec
INSERT INTO dispute_deadlines (dispute_id, kind, cycle, started_at, due_at, basis)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDeadlineParams struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	Basis     string
}

func (q *Queries) InsertDeadline(ctx context.Context, arg InsertDeadlineParams) error {
	_, err := q.db.Exec(ctx, insertDeadline,
		arg.DisputeID,
		arg.Kind,
		arg.Cycle,
		arg.StartedAt,
		arg.DueAt,
		arg.Basis,
	)
	return err
}

const insertDispute = `-- name: InsertDispute :exec
INSERT INTO disputes (id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
`

type InsertDisputeParams struct {
	ID             uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) error {
	_, err := q.db.Exec(ctx, insertDispute,
		arg.ID,
		arg.Regime,
		arg.State,
		arg.Appeals,
		arg.Version,
		arg.TransactionID,
		arg.AccountID,
		arg.DisputedAmount,
		arg.Currency,
		arg.OpenedAt,
	)
	return err
}

const insertDisputeEvent = `-- name: InsertDisputeEvent :one
INSERT INTO dispute_events (dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertDisputeEventParams struct {
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) InsertDisputeEvent(ctx context.Context, arg InsertDisputeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDisputeEvent,
		arg.DisputeID,
		arg.Seq,
		arg.Event,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.Payload,
		arg.IdempotencyKey,
		arg.TraceID,
		arg.OccurredAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (scope, key, request_hash, status_code, response)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyKeyParams struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.Response,
	)
	return err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (dispute_id, seq, kind, debit_account, credit_account, amount, currency, reference, posted_at,
                            core_rrn, core_response_code, core_latency_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertLedgerEntryParams struct {
	DisputeID        uuid.UUID
	Seq              int32
	Kind             string
	DebitAccount     string
	CreditAccount    string
	Amount           decimal.Decimal
	Currency         string
	Reference        string
	PostedAt         time.Time
	CoreRrn          *string
	CoreResponseCode *string
	CoreLatencyMs    *int32
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.DisputeID,
		arg.Seq,
		arg.Kind,
		arg.DebitAccount,
		arg.CreditAccount,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.PostedAt,
		arg.CoreRrn,
		arg.CoreResponseCode,
		arg.CoreLatencyMs,
	)
	return err
}

const insertTenantKey = `-- name: InsertTenantKey :exec
INSERT INTO tenant_keys (id, tenant_id, key_hash, prefix, label, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTenantKeyParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	KeyHash   []byte
	Prefix    string
	Label     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertTenantKey(ctx context.Context, arg InsertTenantKeyParams) error {
	_, err := q.db.Exec(ctx, insertTenantKey,
		arg.ID,
		arg.TenantID,
		arg.KeyHash,
		arg.Prefix,
		arg.Label,
		arg.ExpiresAt,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (id, tenant_id, account_id, rail, amount, currency, merchant, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertTransactionParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	AccountID  uuid.UUID
	Rail       string
	Amount     decimal.Decimal
	Currency   string
	Merchant   string
	OccurredAt time.Time
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Rail,
		arg.Amount,
		arg.Currency,
		arg.Merchant,
		arg.OccurredAt,
	)
	return err
}

const listDeadlines = `-- name: ListDeadlines :many
SELECT dispute_id, kind, cycle, started_at, due_at, met_at, voided_at, basis
FROM dispute_deadlines
WHERE dispute_id = $1
ORDER BY cycle, started_at, kind
`

type ListDeadlinesRow struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	MetAt     pgtype.Timestamptz
	VoidedAt  pgtype.Timestamptz
	Basis     string
}

func (q *Queries) ListDeadlines(ctx context.Context, disputeID uuid.UUID) ([]ListDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listDeadlines, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeadlinesRow{}
	for rows.Next() {
		var i ListDeadlinesRow
		if err := rows.Scan(
			&i.DisputeID,
			&i.Kind,
			&i.Cycle,
			&i.StartedAt,
			&i.DueAt,
			&i.MetAt,
			&i.VoidedAt,
			&i.Basis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputeEvents = `-- name: ListDisputeEvents :many
SELECT id, dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at
FROM dispute_events
WHERE dispute_id = $1
ORDER BY seq
`

type ListDisputeEventsRow struct {
	ID             int64
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) ListDisputeEvents(ctx context.Context, disputeID uuid.UUID) ([]ListDisputeEventsRow, error) {
	rows, err := q.db.Query(ctx, listDisputeEvents, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputeEventsRow{}
	for rows.Next() {
		var i ListDisputeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Event,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Payload,
			&i.IdempotencyKey,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputes = `-- name: ListDisputes :many
SELECT id, regime, state, transaction_id, disputed_amount, currency, opened_at, updated_at
FROM disputes
WHERE ($1::text IS NULL OR state = $1::text)
  AND (NOT $2::boolean OR EXISTS (
        SELECT 1 FROM dispute_deadlines dl
        WHERE dl.dispute_id = disputes.id AND dl.met_at IS NULL AND dl.voided_at IS NULL AND dl.due_at < $3::timestamptz))
  AND ($4::timestamptz IS NULL OR (opened_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY opened_at DESC, id DESC
LIMIT $6
`

type ListDisputesParams struct {
	State          *string
	Overdue        bool
	Now            time.Time
	BeforeOpenedAt pgtype.Timestamptz
	BeforeID       pgtype.UUID
	PageSize       int32
}

type ListDisputesRow struct {
	ID             uuid.UUID
	Regime         string
	State          string
	TransactionID  uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
}

// Keyset pagination on (opened_at, id) descending; row-level security scopes the tenant.
func (q *Queries) ListDisputes(ctx context.Context, arg ListDisputesParams) ([]ListDisputesRow, error) {
	rows, err := q.db.Query(ctx, listDisputes,
		arg.State,
		arg.Overdue,
		arg.Now,
		arg.BeforeOpenedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesRow{}
	for rows.Next() {
		var i ListDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.Regime,
			&i.State,
			&i.TransactionID,
			&i.DisputedAmount,
			&i.Currency,
			&i.OpenedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, dispute_id, seq, kind, debit_account, credit_account, amount, currency, reference, posted_at,
       core_rrn, core_response_code, core_latency_ms
FROM ledger_entries
WHERE dispute_id = $1
ORDER BY id
`

type ListLedgerEntriesRow struct {
	ID               int64
	DisputeID        uuid.UUID
	Seq              int32
	Kind             string
	DebitAccount     string
	CreditAccount    string
	Amount           decimal.Decimal
	Currency         string
	Reference        string
	PostedAt         time.Time
	CoreRrn          *string
	CoreResponseCode *string
	CoreLatencyMs    *int32
}

func (q *Queries) ListLedgerEntries(ctx context.Context, disputeID uuid.UUID) ([]ListLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesRow{}
	for rows.Next() {
		var i ListLedgerEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Kind,
			&i.DebitAccount,
			&i.CreditAccount,
			&i.Amount,
			&i.Currency,
			&i.Reference,
			&i.PostedAt,
			&i.CoreRrn,
			&i.CoreResponseCode,
			&i.CoreLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantKeys = `-- name: ListTenantKeys :many
SELECT id, tenant_id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys ORDER BY created_at
`

type ListTenantKeysRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListTenantKeys(ctx context.Context) ([]ListTenantKeysRow, error) {
	rows, err := q.db.Query(ctx, listTenantKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantKeysRow{}
	for rows.Next() {
		var i ListTenantKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantKeysByTenant = `-- name: ListTenantKeysByTenant :many
SELECT id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys WHERE tenant_id = $1 ORDER BY created_at
`

type ListTenantKeysByTenantRow struct {
	ID         uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListTenantKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListTenantKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listTenantKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantKeysByTenantRow{}
	for rows.Next() {
		var i ListTenantKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, oidc_issuer, disabled_at FROM tenants ORDER BY name
`

type ListTenantsRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
	DisabledAt pgtype.Timestamptz
}

func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OidcIssuer,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForDiscovery = `-- name: ListTenantsForDiscovery :many
SELECT id, name, slug, oidc_issuer, email_domains FROM tenants WHERE disabled_at IS NULL ORDER BY name
`

type ListTenantsForDiscoveryRow struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	OidcIssuer   *string
	EmailDomains []string
}

func (q *Queries) ListTenantsForDiscovery(ctx context.Context) ([]ListTenantsForDiscoveryRow, error) {
	rows, err := q.db.Query(ctx, listTenantsForDiscovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsForDiscoveryRow{}
	for rows.Next() {
		var i ListTenantsForDiscoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OidcIssuer,
			&i.EmailDomains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDeadlines = `-- name: NextDeadlines :many
SELECT DISTINCT ON (dispute_id) dispute_id, kind, cycle, started_at, due_at, met_at, voided_at, basis
FROM dispute_deadlines
WHERE dispute_id = ANY($1::uuid[]) AND met_at IS NULL AND voided_at IS NULL
ORDER BY dispute_id, due_at
`

type NextDeadlinesRow struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	MetAt     pgtype.Timestamptz
	VoidedAt  pgtype.Timestamptz
	Basis     string
}

// The earliest open clock for each dispute in the set; a dispute with none has no row.
func (q *Queries) NextDeadlines(ctx context.Context, disputeIds []uuid.UUID) ([]NextDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, nextDeadlines, disputeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextDeadlinesRow{}
	for rows.Next() {
		var i NextDeadlinesRow
		if err := rows.Scan(
			&i.DisputeID,
			&i.Kind,
			&i.Cycle,
			&i.StartedAt,
			&i.DueAt,
			&i.MetAt,
			&i.VoidedAt,
			&i.Basis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :one
SELECT purge_idempotency_keys($1)::bigint AS n
`

func (q *Queries) PurgeIdempotencyKeys(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, purgeIdempotencyKeys, before)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const purgeTenantRateWindows = `-- name: PurgeTenantRateWindows :execrows
DELETE FROM tenant_rate_windows WHERE window_start < $1
`

func (q *Queries) PurgeTenantRateWindows(ctx context.Context, windowStart time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTenantRateWindows, windowStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWebSessions = `-- name: PurgeWebSessions :execrows
DELETE FROM web_sessions WHERE expires_at < now()
`

func (q *Queries) PurgeWebSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putWebSession = `-- name: PutWebSession :exec
INSERT INTO web_sessions (id, tenant_id, ciphertext, expires_at, subject, sid)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET tenant_id = EXCLUDED.tenant_id, ciphertext = EXCLUDED.ciphertext, expires_at = EXCLUDED.expires_at,
  subject = EXCLUDED.subject, sid = EXCLUDED.sid, updated_at = now()
`

type PutWebSessionParams struct {
	ID         uuid.UUID
	TenantID   pgtype.UUID
	Ciphertext []byte
	ExpiresAt  time.Time
	Subject    *string
	Sid        *string
}

func (q *Queries) PutWebSession(ctx context.Context, arg PutWebSessionParams) error {
	_, err := q.db.Exec(ctx, putWebSession,
		arg.ID,
		arg.TenantID,
		arg.Ciphertext,
		arg.ExpiresAt,
		arg.Subject,
		arg.Sid,
	)
	return err
}

const revokeTenantKey = `-- name: RevokeTenantKey :execrows
UPDATE tenant_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeTenantKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTenantKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTenantKeyForTenant = `-- name: RevokeTenantKeyForTenant :execrows
UPDATE tenant_keys SET revoked_at = now() WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeTenantKeyForTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeTenantKeyForTenant(ctx context.Context, arg RevokeTenantKeyForTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTenantKeyForTenant, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantCalendar = `-- name: SetTenantCalendar :execrows
UPDATE tenants
SET settings = settings || jsonb_build_object('timezone', $1::text, 'holidays', to_jsonb($2::text[]))
WHERE id = $3
`

type SetTenantCalendarParams struct {
	Timezone string
	Holidays []string
	ID       uuid.UUID
}

// The business-day calendar the regulatory clocks use (docs/adr/0013); other settings keys are left alone.
func (q *Queries) SetTenantCalendar(ctx context.Context, arg SetTenantCalendarParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantCalendar, arg.Timezone, arg.Holidays, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantCore = `-- name: SetTenantCore :execrows
UPDATE tenants SET settings = settings || jsonb_build_object('core', $1::jsonb) WHERE id = $2
`

type SetTenantCoreParams struct {
	Core []byte
	ID   uuid.UUID
}

func (q *Queries) SetTenantCore(ctx context.Context, arg SetTenantCoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantCore, arg.Core, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantDisabled = `-- name: SetTenantDisabled :execrows
UPDATE tenants SET disabled_at = CASE WHEN $1::boolean THEN COALESCE(disabled_at, now()) ELSE NULL END WHERE id = $2
`

type SetTenantDisabledParams struct {
	Disabled bool
	ID       uuid.UUID
}

func (q *Queries) SetTenantDisabled(ctx context.Context, arg SetTenantDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantDisabled, arg.Disabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantEmailDomains = `-- name: SetTenantEmailDomains :execrows
UPDATE tenants SET email_domains = $2 WHERE id = $1
`

type SetTenantEmailDomainsParams struct {
	ID           uuid.UUID
	EmailDomains []string
}

func (q *Queries) SetTenantEmailDomains(ctx context.Context, arg SetTenantEmailDomainsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantEmailDomains, arg.ID, arg.EmailDomains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleDeadline = `-- name: SettleDeadline :execrows
UPDATE dispute_deadlines
SET met_at = CASE WHEN $1::boolean THEN $2::timestamptz ELSE met_at END,
    voided_at = CASE WHEN $1::boolean THEN voided_at ELSE $2::timestamptz END
WHERE dispute_id = $3 AND kind = $4 AND cycle = $5 AND met_at IS NULL AND voided_at IS NULL
`

type SettleDeadlineParams struct {
	Met       bool
	At        time.Time
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
}

func (q *Queries) SettleDeadline(ctx context.Context, arg SettleDeadlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleDeadline,
		arg.Met,
		arg.At,
		arg.DisputeID,
		arg.Kind,
		arg.Cycle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspenseByRegime = `-- name: SuspenseByRegime :many
SELECT tenant_id, regime, currency, balance::numeric AS balance FROM suspense_by_regime
`

type SuspenseByRegimeRow struct {
	TenantID uuid.UUID
	Regime   string
	Currency string
	Balance  decimal.Decimal
}

func (q *Queries) SuspenseByRegime(ctx context.Context) ([]SuspenseByRegimeRow, error) {
	rows, err := q.db.Query(ctx, suspenseByRegime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuspenseByRegimeRow{}
	for rows.Next() {
		var i SuspenseByRegimeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.Currency,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTenantKey = `-- name: TouchTenantKey :exec
UPDATE tenant_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchTenantKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTenantKey, id)
	return err
}

const updateDisputeState = `-- name: UpdateDisputeState :execrows
UPDATE disputes
SET state = $2, appeals = $3, version = version + 1, updated_at = $4
WHERE id = $1 AND version = $5
`

type UpdateDisputeStateParams struct {
	ID        uuid.UUID
	State     string
	Appeals   int32
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) UpdateDisputeState(ctx context.Context, arg UpdateDisputeStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDisputeState,
		arg.ID,
		arg.State,
		arg.Appeals,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name, slug, oidc_issuer) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, oidc_issuer = EXCLUDED.oidc_issuer
`

type UpsertTenantParams struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.Exec(ctx, upsertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OidcIssuer,
	)
	return err
}
