// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const answerQuestionnaire = `-- name: AnswerQuestionnaire :execrows
UPDATE questionnaires SET answers = $2, received_at = $3 WHERE dispute_id = $1 AND received_at IS NULL
`

type AnswerQuestionnaireParams struct {
	DisputeID  uuid.UUID
	Answers    []byte
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) AnswerQuestionnaire(ctx context.Context, arg AnswerQuestionnaireParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerQuestionnaire, arg.DisputeID, arg.Answers, arg.ReceivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpTenantRateWindow = `-- name: BumpTenantRateWindow :one
INSERT INTO tenant_rate_windows (tenant_id, window_start, count) VALUES ($1, $2, 1)
ON CONFLICT (tenant_id, window_start) DO UPDATE SET count = tenant_rate_windows.count + 1
RETURNING count
`

type BumpTenantRateWindowParams struct {
	TenantID    uuid.UUID
	WindowStart time.Time
}

func (q *Queries) BumpTenantRateWindow(ctx context.Context, arg BumpTenantRateWindowParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpTenantRateWindow, arg.TenantID, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const claimAttachments = `-- name: ClaimAttachments :execrows
UPDATE attachments SET notice_id = $1
WHERE dispute_id = $2 AND notice_id IS NULL AND id = ANY($3::uuid[])
`

type ClaimAttachmentsParams struct {
	NoticeID  *int64
	DisputeID uuid.UUID
	Ids       []uuid.UUID
}

// Drafts of this dispute only; a claimed attachment belongs to its notice for good.
func (q *Queries) ClaimAttachments(ctx context.Context, arg ClaimAttachmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAttachments, arg.NoticeID, arg.DisputeID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNotices = `-- name: ClaimNotices :many
SELECT id, tenant_id, dispute_id, seq, kind, channel, recipient, subject, document, created_at, attempts, trace_context FROM claim_notices($1)
`

type ClaimNoticesRow struct {
	ID           int64
	TenantID     uuid.UUID
	DisputeID    uuid.UUID
	Seq          int32
	Kind         string
	Channel      string
	Recipient    string
	Subject      string
	Document     []byte
	CreatedAt    time.Time
	Attempts     int32
	TraceContext *string
}

func (q *Queries) ClaimNotices(ctx context.Context, batch int32) ([]ClaimNoticesRow, error) {
	rows, err := q.db.Query(ctx, claimNotices, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimNoticesRow{}
	for rows.Next() {
		var i ClaimNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisputeID,
			&i.Seq,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Document,
			&i.CreatedAt,
			&i.Attempts,
			&i.TraceContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccountDisputesSince = `-- name: CountAccountDisputesSince :one
SELECT count(*)::int FROM disputes WHERE account_id = $1 AND opened_at >= $2 AND id <> $3
`

type CountAccountDisputesSinceParams struct {
	AccountID uuid.UUID
	OpenedAt  time.Time
	ID        uuid.UUID
}

func (q *Queries) CountAccountDisputesSince(ctx context.Context, arg CountAccountDisputesSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAccountDisputesSince, arg.AccountID, arg.OpenedAt, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAccountLostChargebacks = `-- name: CountAccountLostChargebacks :one
SELECT count(DISTINCT d.id)::int FROM disputes d
JOIN dispute_events e ON e.dispute_id = d.id
WHERE d.account_id = $1 AND d.id <> $2 AND e.to_state = 'CHARGEBACK_LOST'
`

type CountAccountLostChargebacksParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) CountAccountLostChargebacks(ctx context.Context, arg CountAccountLostChargebacksParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAccountLostChargebacks, arg.AccountID, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countDeadlinesOverdue = `-- name: CountDeadlinesOverdue :many
SELECT tenant_id, regime, kind, n FROM deadlines_overdue
`

func (q *Queries) CountDeadlinesOverdue(ctx context.Context) ([]DeadlinesOverdue, error) {
	rows, err := q.db.Query(ctx, countDeadlinesOverdue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadlinesOverdue{}
	for rows.Next() {
		var i DeadlinesOverdue
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.Kind,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDisputesByState = `-- name: CountDisputesByState :many
SELECT tenant_id, regime, state, n FROM disputes_by_state
`

func (q *Queries) CountDisputesByState(ctx context.Context) ([]DisputesByState, error) {
	rows, err := q.db.Query(ctx, countDisputesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisputesByState{}
	for rows.Next() {
		var i DisputesByState
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.State,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTenantTemplate = `-- name: DeleteTenantTemplate :execrows
DELETE FROM tenant_templates WHERE kind = $1
`

func (q *Queries) DeleteTenantTemplate(ctx context.Context, kind string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenantTemplate, kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSession = `-- name: DeleteWebSession :execrows
DELETE FROM web_sessions WHERE id = $1
`

func (q *Queries) DeleteWebSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsBySid = `-- name: DeleteWebSessionsBySid :execrows
DELETE FROM web_sessions WHERE sid = $1
`

func (q *Queries) DeleteWebSessionsBySid(ctx context.Context, sid *string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsBySid, sid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsBySubject = `-- name: DeleteWebSessionsBySubject :execrows
DELETE FROM web_sessions WHERE tenant_id = $1 AND subject = $2
`

type DeleteWebSessionsBySubjectParams struct {
	TenantID pgtype.UUID
	Subject  *string
}

func (q *Queries) DeleteWebSessionsBySubject(ctx context.Context, arg DeleteWebSessionsBySubjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsBySubject, arg.TenantID, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebSessionsByTenant = `-- name: DeleteWebSessionsByTenant :execrows
DELETE FROM web_sessions WHERE tenant_id = $1
`

func (q *Queries) DeleteWebSessionsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebSessionsByTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTenantKeyByHash = `-- name: FindTenantKeyByHash :one
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE key_hash = $1
`

type FindTenantKeyByHashRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeyByHash(ctx context.Context, keyHash []byte) (FindTenantKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, findTenantKeyByHash, keyHash)
	var i FindTenantKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.RevokedAt,
	)
	return i, err
}

const findTenantKeysByPrefix = `-- name: FindTenantKeysByPrefix :many
SELECT id, tenant_id, label, revoked_at FROM tenant_keys WHERE prefix = $1
`

type FindTenantKeysByPrefixRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindTenantKeysByPrefix(ctx context.Context, prefix string) ([]FindTenantKeysByPrefixRow, error) {
	rows, err := q.db.Query(ctx, findTenantKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTenantKeysByPrefixRow{}
	for rows.Next() {
		var i FindTenantKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishNotice = `-- name: FinishNotice :exec
SELECT finish_notice($1, $2::text)
`

type FinishNoticeParams struct {
	NoticeID int64
	Failure  *string
}

func (q *Queries) FinishNotice(ctx context.Context, arg FinishNoticeParams) error {
	_, err := q.db.Exec(ctx, finishNotice, arg.NoticeID, arg.Failure)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, holder_name, currency, email, postal_address, opened_at FROM accounts WHERE id = $1
`

type GetAccountRow struct {
	ID            uuid.UUID
	HolderName    string
	Currency      string
	Email         *string
	PostalAddress *string
	OpenedAt      time.Time
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.HolderName,
		&i.Currency,
		&i.Email,
		&i.PostalAddress,
		&i.OpenedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, notice_id, filename, content_type, size, content, uploaded_by, uploaded_at FROM attachments WHERE id = $1 AND dispute_id = $2
`

type GetAttachmentParams struct {
	ID        uuid.UUID
	DisputeID uuid.UUID
}

type GetAttachmentRow struct {
	ID          uuid.UUID
	NoticeID    *int64
	Filename    string
	ContentType string
	Size        int32
	Content     []byte
	UploadedBy  string
	UploadedAt  time.Time
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.ID, arg.DisputeID)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.NoticeID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Content,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, tenant_id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at, reason
FROM disputes
WHERE id = $1
`

type GetDisputeRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
	Reason         string
}

func (q *Queries) GetDispute(ctx context.Context, id uuid.UUID) (GetDisputeRow, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i GetDisputeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Regime,
		&i.State,
		&i.Appeals,
		&i.Version,
		&i.TransactionID,
		&i.AccountID,
		&i.DisputedAmount,
		&i.Currency,
		&i.OpenedAt,
		&i.UpdatedAt,
		&i.Reason,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT scope, key, request_hash, status_code, response, created_at
FROM idempotency_keys
WHERE scope = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	Scope string
	Key   string
}

type GetIdempotencyKeyRow struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
	CreatedAt   time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getNotice = `-- name: GetNotice :one
SELECT id, dispute_id, seq, kind, channel, recipient, subject, document, created_at, sent_at, attempts, last_error, actor, resend_of
FROM notices WHERE id = $1 AND dispute_id = $2
`

type GetNoticeParams struct {
	ID        int64
	DisputeID uuid.UUID
}

type GetNoticeRow struct {
	ID        int64
	DisputeID uuid.UUID
	Seq       int32
	Kind      string
	Channel   string
	Recipient string
	Subject   string
	Document  []byte
	CreatedAt time.Time
	SentAt    pgtype.Timestamptz
	Attempts  int32
	LastError *string
	Actor     *string
	ResendOf  *int64
}

func (q *Queries) GetNotice(ctx context.Context, arg GetNoticeParams) (GetNoticeRow, error) {
	row := q.db.QueryRow(ctx, getNotice, arg.ID, arg.DisputeID)
	var i GetNoticeRow
	err := row.Scan(
		&i.ID,
		&i.DisputeID,
		&i.Seq,
		&i.Kind,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Document,
		&i.CreatedAt,
		&i.SentAt,
		&i.Attempts,
		&i.LastError,
		&i.Actor,
		&i.ResendOf,
	)
	return i, err
}

const getQuestionnaire = `-- name: GetQuestionnaire :one
SELECT dispute_id, reason, questions, answers, sent_at, received_at FROM questionnaires WHERE dispute_id = $1
`

type GetQuestionnaireRow struct {
	DisputeID  uuid.UUID
	Reason     string
	Questions  []byte
	Answers    []byte
	SentAt     time.Time
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) GetQuestionnaire(ctx context.Context, disputeID uuid.UUID) (GetQuestionnaireRow, error) {
	row := q.db.QueryRow(ctx, getQuestionnaire, disputeID)
	var i GetQuestionnaireRow
	err := row.Scan(
		&i.DisputeID,
		&i.Reason,
		&i.Questions,
		&i.Answers,
		&i.SentAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getTenantByIssuer = `-- name: GetTenantByIssuer :one
SELECT id, slug FROM tenants WHERE oidc_issuer = $1 AND disabled_at IS NULL
`

type GetTenantByIssuerRow struct {
	ID   uuid.UUID
	Slug string
}

func (q *Queries) GetTenantByIssuer(ctx context.Context, oidcIssuer *string) (GetTenantByIssuerRow, error) {
	row := q.db.QueryRow(ctx, getTenantByIssuer, oidcIssuer)
	var i GetTenantByIssuerRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getTenantByTenantKeyHash = `-- name: GetTenantByTenantKeyHash :one
SELECT k.id, k.tenant_id FROM tenant_keys k
JOIN tenants t ON t.id = k.tenant_id AND t.disabled_at IS NULL
WHERE k.key_hash = $1 AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetTenantByTenantKeyHashRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetTenantByTenantKeyHash(ctx context.Context, keyHash []byte) (GetTenantByTenantKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getTenantByTenantKeyHash, keyHash)
	var i GetTenantByTenantKeyHashRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const getTenantCalendar = `-- name: GetTenantCalendar :one
SELECT COALESCE(settings->>'timezone', '')::text AS timezone,
       COALESCE(ARRAY(SELECT jsonb_array_elements_text(settings->'holidays')), '{}')::text[] AS holidays
FROM tenants WHERE id = current_tenant_id()
`

type GetTenantCalendarRow struct {
	Timezone string
	Holidays []string
}

func (q *Queries) GetTenantCalendar(ctx context.Context) (GetTenantCalendarRow, error) {
	row := q.db.QueryRow(ctx, getTenantCalendar)
	var i GetTenantCalendarRow
	err := row.Scan(&i.Timezone, &i.Holidays)
	return i, err
}

const getTenantCore = `-- name: GetTenantCore :one
SELECT COALESCE(settings->'core'->>'kind', '')::text AS kind, COALESCE(settings->'core', '{}'::jsonb)::jsonb AS settings
FROM tenants WHERE id = current_tenant_id()
`

type GetTenantCoreRow struct {
	Kind     string
	Settings []byte
}

func (q *Queries) GetTenantCore(ctx context.Context) (GetTenantCoreRow, error) {
	row := q.db.QueryRow(ctx, getTenantCore)
	var i GetTenantCoreRow
	err := row.Scan(&i.Kind, &i.Settings)
	return i, err
}

const getTenantKeyForTenant = `-- name: GetTenantKeyForTenant :one
SELECT id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys WHERE id = $1 AND tenant_id = $2
`

type GetTenantKeyForTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetTenantKeyForTenantRow struct {
	ID         uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) GetTenantKeyForTenant(ctx context.Context, arg GetTenantKeyForTenantParams) (GetTenantKeyForTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenantKeyForTenant, arg.ID, arg.TenantID)
	var i GetTenantKeyForTenantRow
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTenantName = `-- name: GetTenantName :one
SELECT name FROM tenants WHERE id = current_tenant_id()
`

func (q *Queries) GetTenantName(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getTenantName)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.account_id, t.rail, t.amount, t.currency, t.merchant, t.occurred_at, t.mcc, a.currency AS account_currency, a.opened_at AS account_opened_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.id = $1
`

type GetTransactionRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	Rail            string
	Amount          decimal.Decimal
	Currency        string
	Merchant        string
	OccurredAt      time.Time
	Mcc             *string
	AccountCurrency string
	AccountOpenedAt time.Time
}

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Rail,
		&i.Amount,
		&i.Currency,
		&i.Merchant,
		&i.OccurredAt,
		&i.Mcc,
		&i.AccountCurrency,
		&i.AccountOpenedAt,
	)
	return i, err
}

const getWebSession = `-- name: GetWebSession :one
SELECT id, tenant_id, ciphertext, expires_at FROM web_sessions WHERE id = $1 AND expires_at > now()
`

type GetWebSessionRow struct {
	ID         uuid.UUID
	TenantID   pgtype.UUID
	Ciphertext []byte
	ExpiresAt  time.Time
}

func (q *Queries) GetWebSession(ctx context.Context, id uuid.UUID) (GetWebSessionRow, error) {
	row := q.db.QueryRow(ctx, getWebSession, id)
	var i GetWebSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Ciphertext,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, tenant_id, holder_name, currency, email, postal_address) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, postal_address = EXCLUDED.postal_address
`

type InsertAccountParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	HolderName    string
	Currency      string
	Email         *string
	PostalAddress *string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.TenantID,
		arg.HolderName,
		arg.Currency,
		arg.Email,
		arg.PostalAddress,
	)
	return err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO attachments (id, dispute_id, filename, content_type, size, content, uploaded_by, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	DisputeID   uuid.UUID
	Filename    string
	ContentType string
	Size        int32
	Content     []byte
	UploadedBy  string
	UploadedAt  time.Time
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment,
		arg.ID,
		arg.DisputeID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Content,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	return err
}

const insertDeadline = `-- name: InsertDeadline :exec
INSERT INTO dispute_deadlines (dispute_id, kind, cycle, started_at, due_at, basis)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDeadlineParams struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	Basis     string
}

func (q *Queries) InsertDeadline(ctx context.Context, arg InsertDeadlineParams) error {
	_, err := q.db.Exec(ctx, insertDeadline,
		arg.DisputeID,
		arg.Kind,
		arg.Cycle,
		arg.StartedAt,
		arg.DueAt,
		arg.Basis,
	)
	return err
}

const insertDispute = `-- name: InsertDispute :exec
INSERT INTO disputes (id, regime, state, appeals, version, transaction_id, account_id, disputed_amount, currency, opened_at, updated_at, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10, $11)
`

type InsertDisputeParams struct {
	ID             uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	Reason         string
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) error {
	_, err := q.db.Exec(ctx, insertDispute,
		arg.ID,
		arg.Regime,
		arg.State,
		arg.Appeals,
		arg.Version,
		arg.TransactionID,
		arg.AccountID,
		arg.DisputedAmount,
		arg.Currency,
		arg.OpenedAt,
		arg.Reason,
	)
	return err
}

const insertDisputeEvent = `-- name: InsertDisputeEvent :one
INSERT INTO dispute_events (dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertDisputeEventParams struct {
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) InsertDisputeEvent(ctx context.Context, arg InsertDisputeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDisputeEvent,
		arg.DisputeID,
		arg.Seq,
		arg.Event,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.Payload,
		arg.IdempotencyKey,
		arg.TraceID,
		arg.OccurredAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (scope, key, request_hash, status_code, response)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyKeyParams struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.Response,
	)
	return err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (dispute_id, seq, kind, debit_account, credit_account, amount, currency, reference, posted_at,
                            core_rrn, core_response_code, core_latency_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertLedgerEntryParams struct {
	DisputeID        uuid.UUID
	Seq              int32
	Kind             string
	DebitAccount     string
	CreditAccount    string
	Amount           decimal.Decimal
	Currency         string
	Reference        string
	PostedAt         time.Time
	CoreRrn          *string
	CoreResponseCode *string
	CoreLatencyMs    *int32
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.DisputeID,
		arg.Seq,
		arg.Kind,
		arg.DebitAccount,
		arg.CreditAccount,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.PostedAt,
		arg.CoreRrn,
		arg.CoreResponseCode,
		arg.CoreLatencyMs,
	)
	return err
}

const insertNotice = `-- name: InsertNotice :one
INSERT INTO notices (dispute_id, seq, kind, channel, recipient, subject, document, created_at, sent_at, actor, resend_of, trace_context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertNoticeParams struct {
	DisputeID    uuid.UUID
	Seq          int32
	Kind         string
	Channel      string
	Recipient    string
	Subject      string
	Document     []byte
	CreatedAt    time.Time
	SentAt       pgtype.Timestamptz
	Actor        *string
	ResendOf     *int64
	TraceContext *string
}

func (q *Queries) InsertNotice(ctx context.Context, arg InsertNoticeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNotice,
		arg.DisputeID,
		arg.Seq,
		arg.Kind,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Document,
		arg.CreatedAt,
		arg.SentAt,
		arg.Actor,
		arg.ResendOf,
		arg.TraceContext,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRiskAssessment = `-- name: InsertRiskAssessment :exec
INSERT INTO risk_assessments (dispute_id, seq, score, tier, signals, assessed_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRiskAssessmentParams struct {
	DisputeID  uuid.UUID
	Seq        int32
	Score      int32
	Tier       string
	Signals    []byte
	AssessedAt time.Time
}

func (q *Queries) InsertRiskAssessment(ctx context.Context, arg InsertRiskAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertRiskAssessment,
		arg.DisputeID,
		arg.Seq,
		arg.Score,
		arg.Tier,
		arg.Signals,
		arg.AssessedAt,
	)
	return err
}

const insertTenantKey = `-- name: InsertTenantKey :exec
INSERT INTO tenant_keys (id, tenant_id, key_hash, prefix, label, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTenantKeyParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	KeyHash   []byte
	Prefix    string
	Label     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertTenantKey(ctx context.Context, arg InsertTenantKeyParams) error {
	_, err := q.db.Exec(ctx, insertTenantKey,
		arg.ID,
		arg.TenantID,
		arg.KeyHash,
		arg.Prefix,
		arg.Label,
		arg.ExpiresAt,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (id, tenant_id, account_id, rail, amount, currency, merchant, occurred_at, mcc)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET mcc = EXCLUDED.mcc
`

type InsertTransactionParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	AccountID  uuid.UUID
	Rail       string
	Amount     decimal.Decimal
	Currency   string
	Merchant   string
	OccurredAt time.Time
	Mcc        *string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.Rail,
		arg.Amount,
		arg.Currency,
		arg.Merchant,
		arg.OccurredAt,
		arg.Mcc,
	)
	return err
}

const latestRiskTiers = `-- name: LatestRiskTiers :many
SELECT DISTINCT ON (dispute_id) dispute_id, score, tier FROM risk_assessments
WHERE dispute_id = ANY($1::uuid[]) ORDER BY dispute_id, id DESC
`

type LatestRiskTiersRow struct {
	DisputeID uuid.UUID
	Score     int32
	Tier      string
}

// The newest assessment per dispute in the set, for list rows.
func (q *Queries) LatestRiskTiers(ctx context.Context, disputeIds []uuid.UUID) ([]LatestRiskTiersRow, error) {
	rows, err := q.db.Query(ctx, latestRiskTiers, disputeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestRiskTiersRow{}
	for rows.Next() {
		var i LatestRiskTiersRow
		if err := rows.Scan(&i.DisputeID, &i.Score, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentMeta = `-- name: ListAttachmentMeta :many
SELECT id, notice_id, filename, content_type, size, uploaded_by, uploaded_at FROM attachments
WHERE dispute_id = $1 AND (notice_id = ANY($2::bigint[]) OR notice_id IS NULL) ORDER BY uploaded_at
`

type ListAttachmentMetaParams struct {
	DisputeID uuid.UUID
	NoticeIds []int64
}

type ListAttachmentMetaRow struct {
	ID          uuid.UUID
	NoticeID    *int64
	Filename    string
	ContentType string
	Size        int32
	UploadedBy  string
	UploadedAt  time.Time
}

func (q *Queries) ListAttachmentMeta(ctx context.Context, arg ListAttachmentMetaParams) ([]ListAttachmentMetaRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentMeta, arg.DisputeID, arg.NoticeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentMetaRow{}
	for rows.Next() {
		var i ListAttachmentMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeadlines = `-- name: ListDeadlines :many
SELECT dispute_id, kind, cycle, started_at, due_at, met_at, voided_at, basis
FROM dispute_deadlines
WHERE dispute_id = $1
ORDER BY cycle, started_at, kind
`

type ListDeadlinesRow struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	MetAt     pgtype.Timestamptz
	VoidedAt  pgtype.Timestamptz
	Basis     string
}

func (q *Queries) ListDeadlines(ctx context.Context, disputeID uuid.UUID) ([]ListDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listDeadlines, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeadlinesRow{}
	for rows.Next() {
		var i ListDeadlinesRow
		if err := rows.Scan(
			&i.DisputeID,
			&i.Kind,
			&i.Cycle,
			&i.StartedAt,
			&i.DueAt,
			&i.MetAt,
			&i.VoidedAt,
			&i.Basis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputeEvents = `-- name: ListDisputeEvents :many
SELECT id, dispute_id, seq, event, from_state, to_state, actor, payload, idempotency_key, trace_id, occurred_at
FROM dispute_events
WHERE dispute_id = $1
ORDER BY seq
`

type ListDisputeEventsRow struct {
	ID             int64
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
}

func (q *Queries) ListDisputeEvents(ctx context.Context, disputeID uuid.UUID) ([]ListDisputeEventsRow, error) {
	rows, err := q.db.Query(ctx, listDisputeEvents, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputeEventsRow{}
	for rows.Next() {
		var i ListDisputeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Event,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Payload,
			&i.IdempotencyKey,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputes = `-- name: ListDisputes :many
SELECT id, regime, state, transaction_id, disputed_amount, currency, opened_at, updated_at, reason
FROM disputes
WHERE ($1::text IS NULL OR state = $1::text)
  AND ($2::text IS NULL OR reason = $2::text)
  AND (NOT $3::boolean OR EXISTS (
        SELECT 1 FROM dispute_deadlines dl
        WHERE dl.dispute_id = disputes.id AND dl.met_at IS NULL AND dl.voided_at IS NULL AND dl.due_at < $4::timestamptz))
  AND ($5::timestamptz IS NULL OR (opened_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY opened_at DESC, id DESC
LIMIT $7
`

type ListDisputesParams struct {
	State          *string
	Reason         *string
	Overdue        bool
	Now            time.Time
	BeforeOpenedAt pgtype.Timestamptz
	BeforeID       pgtype.UUID
	PageSize       int32
}

type ListDisputesRow struct {
	ID             uuid.UUID
	Regime         string
	State          string
	TransactionID  uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
	Reason         string
}

// Keyset pagination on (opened_at, id) descending; row-level security scopes the tenant.
func (q *Queries) ListDisputes(ctx context.Context, arg ListDisputesParams) ([]ListDisputesRow, error) {
	rows, err := q.db.Query(ctx, listDisputes,
		arg.State,
		arg.Reason,
		arg.Overdue,
		arg.Now,
		arg.BeforeOpenedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesRow{}
	for rows.Next() {
		var i ListDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.Regime,
			&i.State,
			&i.TransactionID,
			&i.DisputedAmount,
			&i.Currency,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, dispute_id, seq, kind, debit_account, credit_account, amount, currency, reference, posted_at,
       core_rrn, core_response_code, core_latency_ms
FROM ledger_entries
WHERE dispute_id = $1
ORDER BY id
`

type ListLedgerEntriesRow struct {
	ID               int64
	DisputeID        uuid.UUID
	Seq              int32
	Kind             string
	DebitAccount     string
	CreditAccount    string
	Amount           decimal.Decimal
	Currency         string
	Reference        string
	PostedAt         time.Time
	CoreRrn          *string
	CoreResponseCode *string
	CoreLatencyMs    *int32
}

func (q *Queries) ListLedgerEntries(ctx context.Context, disputeID uuid.UUID) ([]ListLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesRow{}
	for rows.Next() {
		var i ListLedgerEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Kind,
			&i.DebitAccount,
			&i.CreditAccount,
			&i.Amount,
			&i.Currency,
			&i.Reference,
			&i.PostedAt,
			&i.CoreRrn,
			&i.CoreResponseCode,
			&i.CoreLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotices = `-- name: ListNotices :many
SELECT id, dispute_id, seq, kind, channel, recipient, subject, document, created_at, sent_at, attempts, last_error, actor, resend_of
FROM notices WHERE dispute_id = $1 ORDER BY id
`

type ListNoticesRow struct {
	ID        int64
	DisputeID uuid.UUID
	Seq       int32
	Kind      string
	Channel   string
	Recipient string
	Subject   string
	Document  []byte
	CreatedAt time.Time
	SentAt    pgtype.Timestamptz
	Attempts  int32
	LastError *string
	Actor     *string
	ResendOf  *int64
}

func (q *Queries) ListNotices(ctx context.Context, disputeID uuid.UUID) ([]ListNoticesRow, error) {
	rows, err := q.db.Query(ctx, listNotices, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoticesRow{}
	for rows.Next() {
		var i ListNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Document,
			&i.CreatedAt,
			&i.SentAt,
			&i.Attempts,
			&i.LastError,
			&i.Actor,
			&i.ResendOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskAssessments = `-- name: ListRiskAssessments :many
SELECT id, dispute_id, seq, score, tier, signals, assessed_at FROM risk_assessments WHERE dispute_id = $1 ORDER BY id
`

type ListRiskAssessmentsRow struct {
	ID         int64
	DisputeID  uuid.UUID
	Seq        int32
	Score      int32
	Tier       string
	Signals    []byte
	AssessedAt time.Time
}

func (q *Queries) ListRiskAssessments(ctx context.Context, disputeID uuid.UUID) ([]ListRiskAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listRiskAssessments, disputeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRiskAssessmentsRow{}
	for rows.Next() {
		var i ListRiskAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisputeID,
			&i.Seq,
			&i.Score,
			&i.Tier,
			&i.Signals,
			&i.AssessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantKeys = `-- name: ListTenantKeys :many
SELECT id, tenant_id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys ORDER BY created_at
`

type ListTenantKeysRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListTenantKeys(ctx context.Context) ([]ListTenantKeysRow, error) {
	rows, err := q.db.Query(ctx, listTenantKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantKeysRow{}
	for rows.Next() {
		var i ListTenantKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantKeysByTenant = `-- name: ListTenantKeysByTenant :many
SELECT id, prefix, label, created_at, last_used_at, expires_at, revoked_at FROM tenant_keys WHERE tenant_id = $1 ORDER BY created_at
`

type ListTenantKeysByTenantRow struct {
	ID         uuid.UUID
	Prefix     string
	Label      string
	CreatedAt  time.Time
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListTenantKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListTenantKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listTenantKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantKeysByTenantRow{}
	for rows.Next() {
		var i ListTenantKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantTemplates = `-- name: ListTenantTemplates :many
SELECT kind, override, updated_by, updated_at FROM tenant_templates ORDER BY kind
`

type ListTenantTemplatesRow struct {
	Kind      string
	Override  []byte
	UpdatedBy string
	UpdatedAt time.Time
}

func (q *Queries) ListTenantTemplates(ctx context.Context) ([]ListTenantTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTenantTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantTemplatesRow{}
	for rows.Next() {
		var i ListTenantTemplatesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Override,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, oidc_issuer, disabled_at FROM tenants ORDER BY name
`

type ListTenantsRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
	DisabledAt pgtype.Timestamptz
}

func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OidcIssuer,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForDiscovery = `-- name: ListTenantsForDiscovery :many
SELECT id, name, slug, oidc_issuer, email_domains FROM tenants WHERE disabled_at IS NULL ORDER BY name
`

type ListTenantsForDiscoveryRow struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	OidcIssuer   *string
	EmailDomains []string
}

func (q *Queries) ListTenantsForDiscovery(ctx context.Context) ([]ListTenantsForDiscoveryRow, error) {
	rows, err := q.db.Query(ctx, listTenantsForDiscovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsForDiscoveryRow{}
	for rows.Next() {
		var i ListTenantsForDiscoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OidcIssuer,
			&i.EmailDomains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDeadlines = `-- name: NextDeadlines :many
SELECT DISTINCT ON (dispute_id) dispute_id, kind, cycle, started_at, due_at, met_at, voided_at, basis
FROM dispute_deadlines
WHERE dispute_id = ANY($1::uuid[]) AND met_at IS NULL AND voided_at IS NULL
ORDER BY dispute_id, due_at
`

type NextDeadlinesRow struct {
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	MetAt     pgtype.Timestamptz
	VoidedAt  pgtype.Timestamptz
	Basis     string
}

// The earliest open clock for each dispute in the set; a dispute with none has no row.
func (q *Queries) NextDeadlines(ctx context.Context, disputeIds []uuid.UUID) ([]NextDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, nextDeadlines, disputeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextDeadlinesRow{}
	for rows.Next() {
		var i NextDeadlinesRow
		if err := rows.Scan(
			&i.DisputeID,
			&i.Kind,
			&i.Cycle,
			&i.StartedAt,
			&i.DueAt,
			&i.MetAt,
			&i.VoidedAt,
			&i.Basis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noticeAttachments = `-- name: NoticeAttachments :many
SELECT id, filename, content_type, size, content FROM notice_attachments($1)
`

type NoticeAttachmentsRow struct {
	ID          uuid.UUID
	Filename    string
	ContentType string
	Size        int32
	Content     []byte
}

func (q *Queries) NoticeAttachments(ctx context.Context, nid int64) ([]NoticeAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, noticeAttachments, nid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoticeAttachmentsRow{}
	for rows.Next() {
		var i NoticeAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxBacklog = `-- name: OutboxBacklog :one
SELECT outbox_backlog()
`

func (q *Queries) OutboxBacklog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, outboxBacklog)
	var outbox_backlog int64
	err := row.Scan(&outbox_backlog)
	return outbox_backlog, err
}

const purgeDraftAttachments = `-- name: PurgeDraftAttachments :one
SELECT purge_draft_attachments($1)::bigint AS n
`

func (q *Queries) PurgeDraftAttachments(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, purgeDraftAttachments, before)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :one
SELECT purge_idempotency_keys($1)::bigint AS n
`

func (q *Queries) PurgeIdempotencyKeys(ctx context.Context, before time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, purgeIdempotencyKeys, before)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const purgeTenantRateWindows = `-- name: PurgeTenantRateWindows :execrows
DELETE FROM tenant_rate_windows WHERE window_start < $1
`

func (q *Queries) PurgeTenantRateWindows(ctx context.Context, windowStart time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTenantRateWindows, windowStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeWebSessions = `-- name: PurgeWebSessions :execrows
DELETE FROM web_sessions WHERE expires_at < now()
`

func (q *Queries) PurgeWebSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putWebSession = `-- name: PutWebSession :exec
INSERT INTO web_sessions (id, tenant_id, ciphertext, expires_at, subject, sid)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET tenant_id = EXCLUDED.tenant_id, ciphertext = EXCLUDED.ciphertext, expires_at = EXCLUDED.expires_at,
  subject = EXCLUDED.subject, sid = EXCLUDED.sid, updated_at = now()
`

type PutWebSessionParams struct {
	ID         uuid.UUID
	TenantID   pgtype.UUID
	Ciphertext []byte
	ExpiresAt  time.Time
	Subject    *string
	Sid        *string
}

func (q *Queries) PutWebSession(ctx context.Context, arg PutWebSessionParams) error {
	_, err := q.db.Exec(ctx, putWebSession,
		arg.ID,
		arg.TenantID,
		arg.Ciphertext,
		arg.ExpiresAt,
		arg.Subject,
		arg.Sid,
	)
	return err
}

const revokeTenantKey = `-- name: RevokeTenantKey :execrows
UPDATE tenant_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeTenantKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTenantKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTenantKeyForTenant = `-- name: RevokeTenantKeyForTenant :execrows
UPDATE tenant_keys SET revoked_at = now() WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeTenantKeyForTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeTenantKeyForTenant(ctx context.Context, arg RevokeTenantKeyForTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTenantKeyForTenant, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantCalendar = `-- name: SetTenantCalendar :execrows
UPDATE tenants
SET settings = settings || jsonb_build_object('timezone', $1::text, 'holidays', to_jsonb($2::text[]))
WHERE id = $3
`

type SetTenantCalendarParams struct {
	Timezone string
	Holidays []string
	ID       uuid.UUID
}

// The business-day calendar the regulatory clocks use (docs/adr/0013); other settings keys are left alone.
func (q *Queries) SetTenantCalendar(ctx context.Context, arg SetTenantCalendarParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantCalendar, arg.Timezone, arg.Holidays, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantCore = `-- name: SetTenantCore :execrows
UPDATE tenants SET settings = settings || jsonb_build_object('core', $1::jsonb) WHERE id = $2
`

type SetTenantCoreParams struct {
	Core []byte
	ID   uuid.UUID
}

func (q *Queries) SetTenantCore(ctx context.Context, arg SetTenantCoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantCore, arg.Core, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantDisabled = `-- name: SetTenantDisabled :execrows
UPDATE tenants SET disabled_at = CASE WHEN $1::boolean THEN COALESCE(disabled_at, now()) ELSE NULL END WHERE id = $2
`

type SetTenantDisabledParams struct {
	Disabled bool
	ID       uuid.UUID
}

func (q *Queries) SetTenantDisabled(ctx context.Context, arg SetTenantDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantDisabled, arg.Disabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantEmailDomains = `-- name: SetTenantEmailDomains :execrows
UPDATE tenants SET email_domains = $2 WHERE id = $1
`

type SetTenantEmailDomainsParams struct {
	ID           uuid.UUID
	EmailDomains []string
}

func (q *Queries) SetTenantEmailDomains(ctx context.Context, arg SetTenantEmailDomainsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantEmailDomains, arg.ID, arg.EmailDomains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleDeadline = `-- name: SettleDeadline :execrows
UPDATE dispute_deadlines
SET met_at = CASE WHEN $1::boolean THEN $2::timestamptz ELSE met_at END,
    voided_at = CASE WHEN $1::boolean THEN voided_at ELSE $2::timestamptz END
WHERE dispute_id = $3 AND kind = $4 AND cycle = $5 AND met_at IS NULL AND voided_at IS NULL
`

type SettleDeadlineParams struct {
	Met       bool
	At        time.Time
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
}

func (q *Queries) SettleDeadline(ctx context.Context, arg SettleDeadlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleDeadline,
		arg.Met,
		arg.At,
		arg.DisputeID,
		arg.Kind,
		arg.Cycle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suspenseByRegime = `-- name: SuspenseByRegime :many
SELECT tenant_id, regime, currency, balance::numeric AS balance FROM suspense_by_regime
`

type SuspenseByRegimeRow struct {
	TenantID uuid.UUID
	Regime   string
	Currency string
	Balance  decimal.Decimal
}

func (q *Queries) SuspenseByRegime(ctx context.Context) ([]SuspenseByRegimeRow, error) {
	rows, err := q.db.Query(ctx, suspenseByRegime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuspenseByRegimeRow{}
	for rows.Next() {
		var i SuspenseByRegimeRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Regime,
			&i.Currency,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTenantKey = `-- name: TouchTenantKey :exec
UPDATE tenant_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchTenantKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTenantKey, id)
	return err
}

const updateDisputeState = `-- name: UpdateDisputeState :execrows
UPDATE disputes
SET state = $2, appeals = $3, version = version + 1, updated_at = $4
WHERE id = $1 AND version = $5
`

type UpdateDisputeStateParams struct {
	ID        uuid.UUID
	State     string
	Appeals   int32
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) UpdateDisputeState(ctx context.Context, arg UpdateDisputeStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDisputeState,
		arg.ID,
		arg.State,
		arg.Appeals,
		arg.UpdatedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertQuestionnaire = `-- name: UpsertQuestionnaire :exec
INSERT INTO questionnaires (dispute_id, reason, questions, sent_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (dispute_id) DO UPDATE SET reason = EXCLUDED.reason, questions = EXCLUDED.questions, sent_at = EXCLUDED.sent_at,
  answers = NULL, received_at = NULL
`

type UpsertQuestionnaireParams struct {
	DisputeID uuid.UUID
	Reason    string
	Questions []byte
	SentAt    time.Time
}

// Sending again (after an appeal, say) asks afresh: the questions are replaced and any answers cleared.
func (q *Queries) UpsertQuestionnaire(ctx context.Context, arg UpsertQuestionnaireParams) error {
	_, err := q.db.Exec(ctx, upsertQuestionnaire,
		arg.DisputeID,
		arg.Reason,
		arg.Questions,
		arg.SentAt,
	)
	return err
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name, slug, oidc_issuer) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, oidc_issuer = EXCLUDED.oidc_issuer
`

type UpsertTenantParams struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	OidcIssuer *string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.Exec(ctx, upsertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OidcIssuer,
	)
	return err
}

const upsertTenantTemplate = `-- name: UpsertTenantTemplate :exec
INSERT INTO tenant_templates (kind, override, updated_by, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, kind) DO UPDATE SET override = EXCLUDED.override, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
`

type UpsertTenantTemplateParams struct {
	Kind      string
	Override  []byte
	UpdatedBy string
	UpdatedAt time.Time
}

func (q *Queries) UpsertTenantTemplate(ctx context.Context, arg UpsertTenantTemplateParams) error {
	_, err := q.db.Exec(ctx, upsertTenantTemplate,
		arg.Kind,
		arg.Override,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
