// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID            uuid.UUID
	HolderName    string
	Currency      string
	OpenedAt      time.Time
	TenantID      uuid.UUID
	Email         *string
	PostalAddress *string
}

type Attachment struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	DisputeID   uuid.UUID
	NoticeID    *int64
	Filename    string
	ContentType string
	Size        int32
	Content     []byte
	UploadedBy  string
	UploadedAt  time.Time
}

type DeadlinesOverdue struct {
	TenantID uuid.UUID
	Regime   string
	Kind     string
	N        int64
}

type Dispute struct {
	ID             uuid.UUID
	Regime         string
	State          string
	Appeals        int32
	Version        int64
	TransactionID  uuid.UUID
	AccountID      uuid.UUID
	DisputedAmount decimal.Decimal
	Currency       string
	OpenedAt       time.Time
	UpdatedAt      time.Time
	TenantID       uuid.UUID
	Reason         string
}

type DisputeDeadline struct {
	TenantID  uuid.UUID
	DisputeID uuid.UUID
	Kind      string
	Cycle     int32
	StartedAt time.Time
	DueAt     time.Time
	MetAt     pgtype.Timestamptz
	VoidedAt  pgtype.Timestamptz
	Basis     string
}

type DisputeEvent struct {
	ID             int64
	DisputeID      uuid.UUID
	Seq            int32
	Event          string
	FromState      string
	ToState        string
	Actor          string
	Payload        []byte
	IdempotencyKey *string
	TraceID        *string
	OccurredAt     time.Time
	TenantID       uuid.UUID
}

type DisputesByState struct {
	TenantID uuid.UUID
	Regime   string
	State    string
	N        int64
}

type IdempotencyKey struct {
	Scope       string
	Key         string
	RequestHash []byte
	StatusCode  int32
	Response    []byte
	CreatedAt   time.Time
	TenantID    uuid.UUID
}

type LedgerEntry struct {
	ID               int64
	TenantID         uuid.UUID
	DisputeID        uuid.UUID
	Seq              int32
	Kind             string
	DebitAccount     string
	CreditAccount    string
	Amount           decimal.Decimal
	Currency         string
	Reference        string
	PostedAt         time.Time
	CoreRrn          *string
	CoreResponseCode *string
	CoreLatencyMs    *int32
}

type Notice struct {
	ID            int64
	TenantID      uuid.UUID
	DisputeID     uuid.UUID
	Seq           int32
	Kind          string
	Channel       string
	Recipient     string
	Subject       string
	Document      []byte
	CreatedAt     time.Time
	SentAt        pgtype.Timestamptz
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Actor         *string
	ResendOf      *int64
}

type Questionnaire struct {
	TenantID   uuid.UUID
	DisputeID  uuid.UUID
	Reason     string
	Questions  []byte
	Answers    []byte
	SentAt     time.Time
	ReceivedAt pgtype.Timestamptz
}

type RiskAssessment struct {
	ID         int64
	TenantID   uuid.UUID
	DisputeID  uuid.UUID
	Seq        int32
	Score      int32
	Tier       string
	Signals    []byte
	AssessedAt time.Time
}

type SuspenseByRegime struct {
	TenantID uuid.UUID
	Regime   string
	Currency string
	Balance  int32
}

type Tenant struct {
	ID           uuid.UUID
	Name         string
	Settings     []byte
	CreatedAt    time.Time
	Slug         string
	OidcIssuer   *string
	DisabledAt   pgtype.Timestamptz
	EmailDomains []string
}

type TenantKey struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	KeyHash    []byte
	Label      string
	CreatedAt  time.Time
	RevokedAt  pgtype.Timestamptz
	Prefix     string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type TenantRateWindow struct {
	TenantID    uuid.UUID
	WindowStart time.Time
	Count       int32
}

type TenantTemplate struct {
	TenantID  uuid.UUID
	Kind      string
	Override  []byte
	UpdatedBy string
	UpdatedAt time.Time
}

type Transaction struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Rail       string
	Amount     decimal.Decimal
	Currency   string
	Merchant   string
	OccurredAt time.Time
	TenantID   uuid.UUID
	Mcc        *string
}

type WebSession struct {
	ID         uuid.UUID
	TenantID   pgtype.UUID
	Ciphertext []byte
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Subject    *string
	Sid        *string
}
